export default [
  {
    type: "diamond_color",
    category: "gem_material",
    name: "1 gem diamond white 1",
    thumbnail: "assets/thumbnails/1_gem_diamond_white_1.png",
    value: "assets/gem_material/1_gem_diamond_white_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "1 gem diamond white 1",
    thumbnail: "assets/thumbnails/1_gem_diamond_white_1.png",
    value: "assets/gem_material/1_gem_diamond_white_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "1 gem diamond white 3",
    thumbnail: "assets/thumbnails/1_gem_diamond_white_3.png",
    value: "assets/gem_material/1_gem_diamond_white_3.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "emerald",
    category: "gem_material",
    name: "1 gem emerald 1",
    thumbnail: "assets/thumbnails/1_gem_emerald_1.png",
    value: "assets/gem_material/1_gem_emerald_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "emerald",
    category: "gem_material",
    name: "1 gem emerald 2",
    thumbnail: "assets/thumbnails/1_gem_emerald_2.png",
    value: "assets/gem_material/1_gem_emerald_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ruby",
    category: "gem_material",
    name: "1 gem ruby 1",
    thumbnail: "assets/thumbnails/1_gem_ruby_1.png",
    value: "assets/gem_material/1_gem_ruby_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ruby",
    category: "gem_material",
    name: "1 gem ruby 2",
    thumbnail: "assets/thumbnails/1_gem_ruby_2.png",
    value: "assets/gem_material/1_gem_ruby_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "sapphire",
    category: "gem_material",
    name: "1 gem sapphire 1",
    thumbnail: "assets/thumbnails/1_gem_sapphire_1.png",
    value: "assets/gem_material/1_gem_sapphire_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "sapphire",
    category: "gem_material",
    name: "1 gem sapphire 2",
    thumbnail: "assets/thumbnails/1_gem_sapphire_2.png",
    value: "assets/gem_material/1_gem_sapphire_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond black",
    thumbnail: "assets/thumbnails/2_gem_diamond_black.png",
    value: "assets/gem_material/2_gem_diamond_black.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond blue 1",
    thumbnail: "assets/thumbnails/2_gem_diamond_blue_1.png",
    value: "assets/gem_material/2_gem_diamond_blue_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond blue 2",
    thumbnail: "assets/thumbnails/2_gem_diamond_blue_2.png",
    value: "assets/gem_material/2_gem_diamond_blue_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond brown",
    thumbnail: "assets/thumbnails/2_gem_diamond_brown.png",
    value: "assets/gem_material/2_gem_diamond_brown.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond d colorless",
    thumbnail: "assets/thumbnails/2_gem_diamond_d_colorless.png",
    value: "assets/gem_material/2_gem_diamond_d_colorless.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond greem 2",
    thumbnail: "assets/thumbnails/2_gem_diamond_greem_2.png",
    value: "assets/gem_material/2_gem_diamond_greem_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond green 1",
    thumbnail: "assets/thumbnails/2_gem_diamond_green_1.png",
    value: "assets/gem_material/2_gem_diamond_green_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond h nearcolorless",
    thumbnail: "assets/thumbnails/2_gem_diamond_h_nearcolorless.png",
    value: "assets/gem_material/2_gem_diamond_h_nearcolorless.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond k faintyellow",
    thumbnail: "assets/thumbnails/2_gem_diamond_k_faintyellow.png",
    value: "assets/gem_material/2_gem_diamond_k_faintyellow.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond p verylightyellow",
    thumbnail: "assets/thumbnails/2_gem_diamond_p_verylightyellow.png",
    value: "assets/gem_material/2_gem_diamond_p_verylightyellow.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond pink 1",
    thumbnail: "assets/thumbnails/2_gem_diamond_pink_1.png",
    value: "assets/gem_material/2_gem_diamond_pink_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond pink 2",
    thumbnail: "assets/thumbnails/2_gem_diamond_pink_2.png",
    value: "assets/gem_material/2_gem_diamond_pink_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond t lightyellow",
    thumbnail: "assets/thumbnails/2_gem_diamond_t_lightyellow.png",
    value: "assets/gem_material/2_gem_diamond_t_lightyellow.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond yellow 1",
    thumbnail: "assets/thumbnails/2_gem_diamond_yellow_1.png",
    value: "assets/gem_material/2_gem_diamond_yellow_1.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "diamond_color",
    category: "gem_material",
    name: "2 gem diamond yellow 2",
    thumbnail: "assets/thumbnails/2_gem_diamond_yellow_2.png",
    value: "assets/gem_material/2_gem_diamond_yellow_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "amethyst",
    category: "gem_material",
    name: "gem amethyst 2",
    thumbnail: "assets/thumbnails/gem_amethyst_2.png",
    value: "assets/gem_material/gem_amethyst_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "aquamarin",
    category: "gem_material",
    name: "gem aquamarin",
    thumbnail: "assets/thumbnails/gem_aquamarin.png",
    value: "assets/gem_material/gem_aquamarin.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "cabachon",
    category: "gem_material",
    name: "gem cabachon amethyst",
    thumbnail: "assets/thumbnails/gem_cabachon_amethyst.png",
    value: "assets/gem_material/gem_cabachon_amethyst.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "cabachon",
    category: "gem_material",
    name: "gem cabachon emerald",
    thumbnail: "assets/thumbnails/gem_cabachon_emerald.png",
    value: "assets/gem_material/gem_cabachon_emerald.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "cabachon",
    category: "gem_material",
    name: "gem cabachon ruby",
    thumbnail: "assets/thumbnails/gem_cabachon_ruby.png",
    value: "assets/gem_material/gem_cabachon_ruby.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "cabachon",
    category: "gem_material",
    name: "gem cabachon sapphire yellow",
    thumbnail: "assets/thumbnails/gem_cabachon_sapphire_yellow.png",
    value: "assets/gem_material/gem_cabachon_sapphire_yellow.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "cabachon",
    category: "gem_material",
    name: "gem cabachon sapphire",
    thumbnail: "assets/thumbnails/gem_cabachon_sapphire.png",
    value: "assets/gem_material/gem_cabachon_sapphire.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "cabachon",
    category: "gem_material",
    name: "gem cabachon topaz",
    thumbnail: "assets/thumbnails/gem_cabachon_topaz.png",
    value: "assets/gem_material/gem_cabachon_topaz.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "citrine",
    category: "gem_material",
    name: "gem citrine",
    thumbnail: "assets/thumbnails/gem_citrine.png",
    value: "assets/gem_material/gem_citrine.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "garnet",
    category: "gem_material",
    name: "gem garnet red",
    thumbnail: "assets/thumbnails/gem_garnet_red.png",
    value: "assets/gem_material/gem_garnet_red.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "methist",
    category: "gem_material",
    name: "gem gem amethist",
    thumbnail: "assets/thumbnails/gem_gem_amethist.png",
    value: "assets/gem_material/gem_gem_amethist.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "morganit",
    category: "gem_material",
    name: "gem morganit",
    thumbnail: "assets/thumbnails/gem_morganit.png",
    value: "assets/gem_material/gem_morganit.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "peridot",
    category: "gem_material",
    name: "gem peridot",
    thumbnail: "assets/thumbnails/gem_peridot.png",
    value: "assets/gem_material/gem_peridot.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "quartz_smoky",
    category: "gem_material",
    name: "gem quartz smoky",
    thumbnail: "assets/thumbnails/gem_quartz_smoky.png",
    value: "assets/gem_material/gem_quartz_smoky.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "rhodolite_garnet",
    category: "gem_material",
    name: "gem rhodolite garnet",
    thumbnail: "assets/thumbnails/gem_rhodolite_garnet.png",
    value: "assets/gem_material/gem_rhodolite_garnet.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ruby",
    category: "gem_material",
    name: "gem ruby cabachon 2",
    thumbnail: "assets/thumbnails/gem_ruby_cabachon_2.png",
    value: "assets/gem_material/gem_ruby_cabachon_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "sapphire",
    category: "gem_material",
    name: "gem sapphire cabachon 2",
    thumbnail: "assets/thumbnails/gem_sapphire_cabachon_2.png",
    value: "assets/gem_material/gem_sapphire_cabachon_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "sapphire",
    category: "gem_material",
    name: "gem sapphire green",
    thumbnail: "assets/thumbnails/gem_sapphire_green.png",
    value: "assets/gem_material/gem_sapphire_green.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "sapphire",
    category: "gem_material",
    name: "gem sapphire pink",
    thumbnail: "assets/thumbnails/gem_sapphire_pink.png",
    value: "assets/gem_material/gem_sapphire_pink.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "sapphire",
    category: "gem_material",
    name: "gem sapphire yellow",
    thumbnail: "assets/thumbnails/gem_sapphire_yellow.png",
    value: "assets/gem_material/gem_sapphire_yellow.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tansanit",
    category: "gem_material",
    name: "gem tansanit 2",
    thumbnail: "assets/thumbnails/gem_tansanit_2.png",
    value: "assets/gem_material/gem_tansanit_2.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tansanit",
    category: "gem_material",
    name: "gem tansanit",
    thumbnail: "assets/thumbnails/gem_tansanit.png",
    value: "assets/gem_material/gem_tansanit.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "topas",
    category: "gem_material",
    name: "gem topas",
    thumbnail: "assets/thumbnails/gem_topas.png",
    value: "assets/gem_material/gem_topas.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tourmalin",
    category: "gem_material",
    name: "gem tourmalin green",
    thumbnail: "assets/thumbnails/gem_tourmalin_green.png",
    value: "assets/gem_material/gem_tourmalin_green.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tourmalin",
    category: "gem_material",
    name: "gem tourmalin rose",
    thumbnail: "assets/thumbnails/gem_tourmalin_rose.png",
    value: "assets/gem_material/gem_tourmalin_rose.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tsavorit",
    category: "gem_material",
    name: "gem tsavorit",
    thumbnail: "assets/thumbnails/gem_tsavorit.png",
    value: "assets/gem_material/gem_tsavorit.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "zircon",
    category: "gem_material",
    name: "gem zircon blue",
    thumbnail: "assets/thumbnails/gem_zircon_blue.png",
    value: "assets/gem_material/gem_zircon_blue.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "zircon",
    category: "gem_material",
    name: "gem zircon brown",
    thumbnail: "assets/thumbnails/gem_zircon_brown.png",
    value: "assets/gem_material/gem_zircon_brown.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "zircon",
    category: "gem_material",
    name: "gem zircon cinnamon",
    thumbnail: "assets/thumbnails/gem_zircon_cinnamon.png",
    value: "assets/gem_material/gem_zircon_cinnamon.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "zircon",
    category: "gem_material",
    name: "gem zircon green",
    thumbnail: "assets/thumbnails/gem_zircon_green.png",
    value: "assets/gem_material/gem_zircon_green.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "zircon",
    category: "gem_material",
    name: "gem zircon red",
    thumbnail: "assets/thumbnails/gem_zircon_red.png",
    value: "assets/gem_material/gem_zircon_red.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "zircon",
    category: "gem_material",
    name: "gem zircon turquoise",
    thumbnail: "assets/thumbnails/gem_zircon_turquoise.png",
    value: "assets/gem_material/gem_zircon_turquoise.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "zircon",
    category: "gem_material",
    name: "gem zircon white",
    thumbnail: "assets/thumbnails/gem_zircon_white.png",
    value: "assets/gem_material/gem_zircon_white.dmat",
    userId: null,
    weight: 10,
  },
  {
    type: "zircon",
    category: "gem_material",
    name: "gem zircon yellow",
    thumbnail: "assets/thumbnails/gem_zircon_yellow.png",
    value: "assets/gem_material/gem_zircon_yellow.dmat",
    userId: null,
    weight: 10,
  },
];
