export default [
  {
    type: "metal_gold_polished",
    category: "metal_material",
    name: "1 metal gold polished",
    thumbnail: "/assets/thumbnails/1_metal_gold_polished.png",
    value: "/assets/metal_material/1_metal_gold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_rosegold_polished",
    category: "metal_material",
    name: "1 metal rosegold polished",
    thumbnail: "/assets/thumbnails/1_metal_rosegold_polished.png",
    value: "/assets/metal_material/1_metal_rosegold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_whitegold_polished",
    category: "metal_material",
    name: "1 metal whitegold polished",
    thumbnail: "/assets/thumbnails/1_metal_whitegold_polished.png",
    value: "/assets/metal_material/1_metal_whitegold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_blackrhodium_polished",
    category: "metal_material",
    name: "2 metal blackrhodium polished",
    thumbnail: "/assets/thumbnails/2_metal_blackrhodium_polished.png",
    value: "/assets/metal_material/2_metal_blackrhodium_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_gold_09k",
    category: "metal_material",
    name: "2 metal gold 09k",
    thumbnail: "/assets/thumbnails/2_metal_gold_09k.png",
    value: "/assets/metal_material/2_metal_gold_09k.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_gold_14k",
    category: "metal_material",
    name: "2 metal gold 14k",
    thumbnail: "/assets/thumbnails/2_metal_gold_14k.png",
    value: "/assets/metal_material/2_metal_gold_14k.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_gold_22k",
    category: "metal_material",
    name: "2 metal gold 22k",
    thumbnail: "/assets/thumbnails/2_metal_gold_22k.png",
    value: "/assets/metal_material/2_metal_gold_22k.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_greengold_polished",
    category: "metal_material",
    name: "2 metal greengold polished",
    thumbnail: "/assets/thumbnails/2_metal_greengold_polished.png",
    value: "/assets/metal_material/2_metal_greengold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_greygold_polished",
    category: "metal_material",
    name: "2 metal greygold polished",
    thumbnail: "/assets/thumbnails/2_metal_greygold_polished.png",
    value: "/assets/metal_material/2_metal_greygold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_platinum_polished",
    category: "metal_material",
    name: "2 metal platinum polished",
    thumbnail: "/assets/thumbnails/2_metal_platinum_polished.png",
    value: "/assets/metal_material/2_metal_platinum_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_redgold_polished",
    category: "metal_material",
    name: "2 metal redgold polished",
    thumbnail: "/assets/thumbnails/2_metal_redgold_polished.png",
    value: "/assets/metal_material/2_metal_redgold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_redgoldlight_polished",
    category: "metal_material",
    name: "2 metal redgoldlight polished",
    thumbnail: "/assets/thumbnails/2_metal_redgoldlight_polished.png",
    value: "/assets/metal_material/2_metal_redgoldlight_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_rosegold_polished",
    category: "metal_material",
    name: "2 metal rosegold polished",
    thumbnail: "/assets/thumbnails/2_metal_rosegold_polished.png",
    value: "/assets/metal_material/2_metal_rosegold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_sandgold_polished",
    category: "metal_material",
    name: "2 metal sandgold polished",
    thumbnail: "/assets/thumbnails/2_metal_sandgold_polished.png",
    value: "/assets/metal_material/2_metal_sandgold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_silver_polished",
    category: "metal_material",
    name: "2 metal silver polished",
    thumbnail: "/assets/thumbnails/2_metal_silver_polished.png",
    value: "/assets/metal_material/2_metal_silver_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_warmgold_polished",
    category: "metal_material",
    name: "2 metal warmgold polished",
    thumbnail: "/assets/thumbnails/2_metal_warmgold_polished.png",
    value: "/assets/metal_material/2_metal_warmgold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_yellowgold_polished",
    category: "metal_material",
    name: "2 metal yellowgold polished",
    thumbnail: "/assets/thumbnails/2_metal_yellowgold_polished.png",
    value: "/assets/metal_material/2_metal_yellowgold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_black",
    category: "metal_material",
    name: "ceramic black",
    thumbnail: "/assets/thumbnails/ceramic_black.png",
    value: "/assets/metal_material/ceramic_black.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_blue_2",
    category: "metal_material",
    name: "ceramic blue 2",
    thumbnail: "/assets/thumbnails/ceramic_blue_2.png",
    value: "/assets/metal_material/ceramic_blue_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_blue",
    category: "metal_material",
    name: "ceramic blue",
    thumbnail: "/assets/thumbnails/ceramic_blue.png",
    value: "/assets/metal_material/ceramic_blue.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_bluemarine",
    category: "metal_material",
    name: "ceramic bluemarine",
    thumbnail: "/assets/thumbnails/ceramic_bluemarine.png",
    value: "/assets/metal_material/ceramic_bluemarine.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_cyan",
    category: "metal_material",
    name: "ceramic cyan",
    thumbnail: "/assets/thumbnails/ceramic_cyan.png",
    value: "/assets/metal_material/ceramic_cyan.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_green",
    category: "metal_material",
    name: "ceramic green",
    thumbnail: "/assets/thumbnails/ceramic_green.png",
    value: "/assets/metal_material/ceramic_green.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_grey",
    category: "metal_material",
    name: "ceramic grey",
    thumbnail: "/assets/thumbnails/ceramic_grey.png",
    value: "/assets/metal_material/ceramic_grey.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_orange",
    category: "metal_material",
    name: "ceramic orange",
    thumbnail: "/assets/thumbnails/ceramic_orange.png",
    value: "/assets/metal_material/ceramic_orange.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_peach",
    category: "metal_material",
    name: "ceramic peach",
    thumbnail: "/assets/thumbnails/ceramic_peach.png",
    value: "/assets/metal_material/ceramic_peach.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_purple",
    category: "metal_material",
    name: "ceramic purple",
    thumbnail: "/assets/thumbnails/ceramic_purple.png",
    value: "/assets/metal_material/ceramic_purple.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_red_2",
    category: "metal_material",
    name: "ceramic red 2",
    thumbnail: "/assets/thumbnails/ceramic_red_2.png",
    value: "/assets/metal_material/ceramic_red_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_red",
    category: "metal_material",
    name: "ceramic red",
    thumbnail: "/assets/thumbnails/ceramic_red.png",
    value: "/assets/metal_material/ceramic_red.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_rosa",
    category: "metal_material",
    name: "ceramic rosa",
    thumbnail: "/assets/thumbnails/ceramic_rosa.png",
    value: "/assets/metal_material/ceramic_rosa.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_violet",
    category: "metal_material",
    name: "ceramic violet",
    thumbnail: "/assets/thumbnails/ceramic_violet.png",
    value: "/assets/metal_material/ceramic_violet.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_white",
    category: "metal_material",
    name: "ceramic white",
    thumbnail: "/assets/thumbnails/ceramic_white.png",
    value: "/assets/metal_material/ceramic_white.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_yellow_2",
    category: "metal_material",
    name: "ceramic yellow 2",
    thumbnail: "/assets/thumbnails/ceramic_yellow_2.png",
    value: "/assets/metal_material/ceramic_yellow_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ramic_yellow",
    category: "metal_material",
    name: "ceramic yellow",
    thumbnail: "/assets/thumbnails/ceramic_yellow.png",
    value: "/assets/metal_material/ceramic_yellow.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ral_angelskin",
    category: "metal_material",
    name: "coral angelskin",
    thumbnail: "/assets/thumbnails/coral_angelskin.png",
    value: "/assets/metal_material/coral_angelskin.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ral_red",
    category: "metal_material",
    name: "coral red",
    thumbnail: "/assets/thumbnails/coral_red.png",
    value: "/assets/metal_material/coral_red.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "amel_blue_transparent",
    category: "metal_material",
    name: "enamel blue transparent",
    thumbnail: "/assets/thumbnails/enamel_blue_transparent.png",
    value: "/assets/metal_material/enamel_blue_transparent.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "amel_darkblue_transparent",
    category: "metal_material",
    name: "enamel darkblue transparent",
    thumbnail: "/assets/thumbnails/enamel_darkblue_transparent.png",
    value: "/assets/metal_material/enamel_darkblue_transparent.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "amel_green_transparent",
    category: "metal_material",
    name: "enamel green transparent",
    thumbnail: "/assets/thumbnails/enamel_green_transparent.png",
    value: "/assets/metal_material/enamel_green_transparent.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "amel_pink_transparent",
    category: "metal_material",
    name: "enamel pink transparent",
    thumbnail: "/assets/thumbnails/enamel_pink_transparent.png",
    value: "/assets/metal_material/enamel_pink_transparent.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "amel_red_transparent",
    category: "metal_material",
    name: "enamel red transparent",
    thumbnail: "/assets/thumbnails/enamel_red_transparent.png",
    value: "/assets/metal_material/enamel_red_transparent.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_biege_furniture",
    category: "metal_material",
    name: "fabric biege furniture",
    thumbnail: "/assets/thumbnails/fabric_biege_furniture.png",
    value: "/assets/metal_material/fabric_biege_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_black_furniture",
    category: "metal_material",
    name: "fabric black furniture",
    thumbnail: "/assets/thumbnails/fabric_black_furniture.png",
    value: "/assets/metal_material/fabric_black_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_blue_furniture",
    category: "metal_material",
    name: "fabric blue furniture",
    thumbnail: "/assets/thumbnails/fabric_blue_furniture.png",
    value: "/assets/metal_material/fabric_blue_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_brown_furniture",
    category: "metal_material",
    name: "fabric brown furniture",
    thumbnail: "/assets/thumbnails/fabric_brown_furniture.png",
    value: "/assets/metal_material/fabric_brown_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_classic_black",
    category: "metal_material",
    name: "fabric classic black",
    thumbnail: "/assets/thumbnails/fabric_classic_black.png",
    value: "/assets/metal_material/fabric_classic_black.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_classic_blue_1",
    category: "metal_material",
    name: "fabric classic blue 1",
    thumbnail: "/assets/thumbnails/fabric_classic_blue_1.png",
    value: "/assets/metal_material/fabric_classic_blue_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_classic_blue_2",
    category: "metal_material",
    name: "fabric classic blue 2",
    thumbnail: "/assets/thumbnails/fabric_classic_blue_2.png",
    value: "/assets/metal_material/fabric_classic_blue_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_classic_green",
    category: "metal_material",
    name: "fabric classic green",
    thumbnail: "/assets/thumbnails/fabric_classic_green.png",
    value: "/assets/metal_material/fabric_classic_green.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_classic_red",
    category: "metal_material",
    name: "fabric classic red",
    thumbnail: "/assets/thumbnails/fabric_classic_red.png",
    value: "/assets/metal_material/fabric_classic_red.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_classic_turquoise",
    category: "metal_material",
    name: "fabric classic turquoise",
    thumbnail: "/assets/thumbnails/fabric_classic_turquoise.png",
    value: "/assets/metal_material/fabric_classic_turquoise.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_classic_white",
    category: "metal_material",
    name: "fabric classic white",
    thumbnail: "/assets/thumbnails/fabric_classic_white.png",
    value: "/assets/metal_material/fabric_classic_white.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_green_furniture",
    category: "metal_material",
    name: "fabric green furniture",
    thumbnail: "/assets/thumbnails/fabric_green_furniture.png",
    value: "/assets/metal_material/fabric_green_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_grey_furniture",
    category: "metal_material",
    name: "fabric grey furniture",
    thumbnail: "/assets/thumbnails/fabric_grey_furniture.png",
    value: "/assets/metal_material/fabric_grey_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_lightblue_furniture",
    category: "metal_material",
    name: "fabric lightblue furniture",
    thumbnail: "/assets/thumbnails/fabric_lightblue_furniture.png",
    value: "/assets/metal_material/fabric_lightblue_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_lightgreen_furniture",
    category: "metal_material",
    name: "fabric lightgreen furniture",
    thumbnail: "/assets/thumbnails/fabric_lightgreen_furniture.png",
    value: "/assets/metal_material/fabric_lightgreen_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_silk_black",
    category: "metal_material",
    name: "fabric silk black",
    thumbnail: "/assets/thumbnails/fabric_silk_black.png",
    value: "/assets/metal_material/fabric_silk_black.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_silk_blue",
    category: "metal_material",
    name: "fabric silk blue",
    thumbnail: "/assets/thumbnails/fabric_silk_blue.png",
    value: "/assets/metal_material/fabric_silk_blue.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_silk_green",
    category: "metal_material",
    name: "fabric silk green",
    thumbnail: "/assets/thumbnails/fabric_silk_green.png",
    value: "/assets/metal_material/fabric_silk_green.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_silk_red",
    category: "metal_material",
    name: "fabric silk red",
    thumbnail: "/assets/thumbnails/fabric_silk_red.png",
    value: "/assets/metal_material/fabric_silk_red.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_silk_turquoise",
    category: "metal_material",
    name: "fabric silk turquoise",
    thumbnail: "/assets/thumbnails/fabric_silk_turquoise.png",
    value: "/assets/metal_material/fabric_silk_turquoise.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_silk_white",
    category: "metal_material",
    name: "fabric silk white",
    thumbnail: "/assets/thumbnails/fabric_silk_white.png",
    value: "/assets/metal_material/fabric_silk_white.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_velvet_blue_1",
    category: "metal_material",
    name: "fabric velvet blue 1",
    thumbnail: "/assets/thumbnails/fabric_velvet_blue_1.png",
    value: "/assets/metal_material/fabric_velvet_blue_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_velvet_blue_2",
    category: "metal_material",
    name: "fabric velvet blue 2",
    thumbnail: "/assets/thumbnails/fabric_velvet_blue_2.png",
    value: "/assets/metal_material/fabric_velvet_blue_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_velvet_purple",
    category: "metal_material",
    name: "fabric velvet purple",
    thumbnail: "/assets/thumbnails/fabric_velvet_purple.png",
    value: "/assets/metal_material/fabric_velvet_purple.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_velvet_red_1",
    category: "metal_material",
    name: "fabric velvet red 1",
    thumbnail: "/assets/thumbnails/fabric_velvet_red_1.png",
    value: "/assets/metal_material/fabric_velvet_red_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_velvet_red_2",
    category: "metal_material",
    name: "fabric velvet red 2",
    thumbnail: "/assets/thumbnails/fabric_velvet_red_2.png",
    value: "/assets/metal_material/fabric_velvet_red_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_velvet_turquoise",
    category: "metal_material",
    name: "fabric velvet turquoise",
    thumbnail: "/assets/thumbnails/fabric_velvet_turquoise.png",
    value: "/assets/metal_material/fabric_velvet_turquoise.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_velvet_white",
    category: "metal_material",
    name: "fabric velvet white",
    thumbnail: "/assets/thumbnails/fabric_velvet_white.png",
    value: "/assets/metal_material/fabric_velvet_white.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "bric_wine_furniture",
    category: "metal_material",
    name: "fabric wine furniture",
    thumbnail: "/assets/thumbnails/fabric_wine_furniture.png",
    value: "/assets/metal_material/fabric_wine_furniture.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_1",
    category: "metal_material",
    name: "gem achat 1",
    thumbnail: "/assets/thumbnails/gem_achat_1.png",
    value: "/assets/metal_material/gem_achat_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_2",
    category: "metal_material",
    name: "gem achat 2",
    thumbnail: "/assets/thumbnails/gem_achat_2.png",
    value: "/assets/metal_material/gem_achat_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_3",
    category: "metal_material",
    name: "gem achat 3",
    thumbnail: "/assets/thumbnails/gem_achat_3.png",
    value: "/assets/metal_material/gem_achat_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_4",
    category: "metal_material",
    name: "gem achat 4",
    thumbnail: "/assets/thumbnails/gem_achat_4.png",
    value: "/assets/metal_material/gem_achat_4.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_5",
    category: "metal_material",
    name: "gem achat 5",
    thumbnail: "/assets/thumbnails/gem_achat_5.png",
    value: "/assets/metal_material/gem_achat_5.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_6",
    category: "metal_material",
    name: "gem achat 6",
    thumbnail: "/assets/thumbnails/gem_achat_6.png",
    value: "/assets/metal_material/gem_achat_6.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_7",
    category: "metal_material",
    name: "gem achat 7",
    thumbnail: "/assets/thumbnails/gem_achat_7.png",
    value: "/assets/metal_material/gem_achat_7.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_8",
    category: "metal_material",
    name: "gem achat 8",
    thumbnail: "/assets/thumbnails/gem_achat_8.png",
    value: "/assets/metal_material/gem_achat_8.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_achat_9",
    category: "metal_material",
    name: "gem achat 9",
    thumbnail: "/assets/thumbnails/gem_achat_9.png",
    value: "/assets/metal_material/gem_achat_9.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_jade_1",
    category: "metal_material",
    name: "gem jade 1",
    thumbnail: "/assets/thumbnails/gem_jade_1.png",
    value: "/assets/metal_material/gem_jade_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_jade_2",
    category: "metal_material",
    name: "gem jade 2",
    thumbnail: "/assets/thumbnails/gem_jade_2.png",
    value: "/assets/metal_material/gem_jade_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_jasper",
    category: "metal_material",
    name: "gem jasper",
    thumbnail: "/assets/thumbnails/gem_jasper.png",
    value: "/assets/metal_material/gem_jasper.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_lapislazuli_1",
    category: "metal_material",
    name: "gem lapislazuli 1",
    thumbnail: "/assets/thumbnails/gem_lapislazuli_1.png",
    value: "/assets/metal_material/gem_lapislazuli_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_malachite_1",
    category: "metal_material",
    name: "gem malachite 1",
    thumbnail: "/assets/thumbnails/gem_malachite_1.png",
    value: "/assets/metal_material/gem_malachite_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_malachite_2",
    category: "metal_material",
    name: "gem malachite 2",
    thumbnail: "/assets/thumbnails/gem_malachite_2.png",
    value: "/assets/metal_material/gem_malachite_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_malachite_3",
    category: "metal_material",
    name: "gem malachite 3",
    thumbnail: "/assets/thumbnails/gem_malachite_3.png",
    value: "/assets/metal_material/gem_malachite_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_onyx",
    category: "metal_material",
    name: "gem onyx",
    thumbnail: "/assets/thumbnails/gem_onyx.png",
    value: "/assets/metal_material/gem_onyx.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_quartz_rosa",
    category: "metal_material",
    name: "gem quartz rosa",
    thumbnail: "/assets/thumbnails/gem_quartz_rosa.png",
    value: "/assets/metal_material/gem_quartz_rosa.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_turquoise_1",
    category: "metal_material",
    name: "gem turquoise 1",
    thumbnail: "/assets/thumbnails/gem_turquoise_1.png",
    value: "/assets/metal_material/gem_turquoise_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_turquoise_2",
    category: "metal_material",
    name: "gem turquoise 2",
    thumbnail: "/assets/thumbnails/gem_turquoise_2.png",
    value: "/assets/metal_material/gem_turquoise_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "m_turquoise_3",
    category: "metal_material",
    name: "gem turquoise 3",
    thumbnail: "/assets/thumbnails/gem_turquoise_3.png",
    value: "/assets/metal_material/gem_turquoise_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ass_watch_1",
    category: "metal_material",
    name: "glass watch 1",
    thumbnail: "/assets/thumbnails/glass_watch_1.png",
    value: "/assets/metal_material/glass_watch_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ld_texture_smallscratches_rose",
    category: "metal_material",
    name: "gold texture smallscratches rose",
    thumbnail: "/assets/thumbnails/gold_texture_smallscratches_rose.png",
    value: "/assets/metal_material/gold_texture_smallscratches_rose.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ld_texture_smallscratches_white",
    category: "metal_material",
    name: "gold texture smallscratches white",
    thumbnail: "/assets/thumbnails/gold_texture_smallscratches_white.png",
    value: "/assets/metal_material/gold_texture_smallscratches_white.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ld_texture_smallscratches",
    category: "metal_material",
    name: "gold texture smallscratches",
    thumbnail: "/assets/thumbnails/gold_texture_smallscratches.png",
    value: "/assets/metal_material/gold_texture_smallscratches.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ory_1",
    category: "metal_material",
    name: "ivory 1",
    thumbnail: "/assets/thumbnails/ivory_1.png",
    value: "/assets/metal_material/ivory_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ory_2",
    category: "metal_material",
    name: "ivory 2",
    thumbnail: "/assets/thumbnails/ivory_2.png",
    value: "/assets/metal_material/ivory_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_beige",
    category: "metal_material",
    name: "leather beige",
    thumbnail: "/assets/thumbnails/leather_beige.png",
    value: "/assets/metal_material/leather_beige.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_black_crocodile",
    category: "metal_material",
    name: "leather black crocodile",
    thumbnail: "/assets/thumbnails/leather_black_crocodile.png",
    value: "/assets/metal_material/leather_black_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_black_wrinkled",
    category: "metal_material",
    name: "leather black wrinkled",
    thumbnail: "/assets/thumbnails/leather_black_wrinkled.png",
    value: "/assets/metal_material/leather_black_wrinkled.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_black",
    category: "metal_material",
    name: "leather black",
    thumbnail: "/assets/thumbnails/leather_black.png",
    value: "/assets/metal_material/leather_black.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_blue_1_crocodile",
    category: "metal_material",
    name: "leather blue 1 crocodile",
    thumbnail: "/assets/thumbnails/leather_blue_1_crocodile.png",
    value: "/assets/metal_material/leather_blue_1_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_blue_2_crocodile",
    category: "metal_material",
    name: "leather blue 2 crocodile",
    thumbnail: "/assets/thumbnails/leather_blue_2_crocodile.png",
    value: "/assets/metal_material/leather_blue_2_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_blue_marine",
    category: "metal_material",
    name: "leather blue marine",
    thumbnail: "/assets/thumbnails/leather_blue_marine.png",
    value: "/assets/metal_material/leather_blue_marine.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_blue_royal",
    category: "metal_material",
    name: "leather blue royal",
    thumbnail: "/assets/thumbnails/leather_blue_royal.png",
    value: "/assets/metal_material/leather_blue_royal.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_blue_snake",
    category: "metal_material",
    name: "leather blue snake",
    thumbnail: "/assets/thumbnails/leather_blue_snake.png",
    value: "/assets/metal_material/leather_blue_snake.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_brown_1_crocodile",
    category: "metal_material",
    name: "leather brown 1 crocodile",
    thumbnail: "/assets/thumbnails/leather_brown_1_crocodile.png",
    value: "/assets/metal_material/leather_brown_1_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_brown_2_crocodile",
    category: "metal_material",
    name: "leather brown 2 crocodile",
    thumbnail: "/assets/thumbnails/leather_brown_2_crocodile.png",
    value: "/assets/metal_material/leather_brown_2_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_brown_3_crocodile",
    category: "metal_material",
    name: "leather brown 3 crocodile",
    thumbnail: "/assets/thumbnails/leather_brown_3_crocodile.png",
    value: "/assets/metal_material/leather_brown_3_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_brown_wrinkled",
    category: "metal_material",
    name: "leather brown wrinkled",
    thumbnail: "/assets/thumbnails/leather_brown_wrinkled.png",
    value: "/assets/metal_material/leather_brown_wrinkled.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_green_1",
    category: "metal_material",
    name: "leather green 1",
    thumbnail: "/assets/thumbnails/leather_green_1.png",
    value: "/assets/metal_material/leather_green_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_green_2",
    category: "metal_material",
    name: "leather green 2",
    thumbnail: "/assets/thumbnails/leather_green_2.png",
    value: "/assets/metal_material/leather_green_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_green_crocodile",
    category: "metal_material",
    name: "leather green crocodile",
    thumbnail: "/assets/thumbnails/leather_green_crocodile.png",
    value: "/assets/metal_material/leather_green_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_green_snake",
    category: "metal_material",
    name: "leather green snake",
    thumbnail: "/assets/thumbnails/leather_green_snake.png",
    value: "/assets/metal_material/leather_green_snake.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_grey",
    category: "metal_material",
    name: "leather grey",
    thumbnail: "/assets/thumbnails/leather_grey.png",
    value: "/assets/metal_material/leather_grey.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_orange_snake",
    category: "metal_material",
    name: "leather orange snake",
    thumbnail: "/assets/thumbnails/leather_orange_snake.png",
    value: "/assets/metal_material/leather_orange_snake.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_peach",
    category: "metal_material",
    name: "leather peach",
    thumbnail: "/assets/thumbnails/leather_peach.png",
    value: "/assets/metal_material/leather_peach.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_pink",
    category: "metal_material",
    name: "leather pink",
    thumbnail: "/assets/thumbnails/leather_pink.png",
    value: "/assets/metal_material/leather_pink.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_purple",
    category: "metal_material",
    name: "leather purple",
    thumbnail: "/assets/thumbnails/leather_purple.png",
    value: "/assets/metal_material/leather_purple.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_red_1",
    category: "metal_material",
    name: "leather red 1",
    thumbnail: "/assets/thumbnails/leather_red_1.png",
    value: "/assets/metal_material/leather_red_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_red_2",
    category: "metal_material",
    name: "leather red 2",
    thumbnail: "/assets/thumbnails/leather_red_2.png",
    value: "/assets/metal_material/leather_red_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_red_crocodile",
    category: "metal_material",
    name: "leather red crocodile",
    thumbnail: "/assets/thumbnails/leather_red_crocodile.png",
    value: "/assets/metal_material/leather_red_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_red_snake",
    category: "metal_material",
    name: "leather red snake",
    thumbnail: "/assets/thumbnails/leather_red_snake.png",
    value: "/assets/metal_material/leather_red_snake.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_rosa_1",
    category: "metal_material",
    name: "leather rosa 1",
    thumbnail: "/assets/thumbnails/leather_rosa_1.png",
    value: "/assets/metal_material/leather_rosa_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_rosa_2",
    category: "metal_material",
    name: "leather rosa 2",
    thumbnail: "/assets/thumbnails/leather_rosa_2.png",
    value: "/assets/metal_material/leather_rosa_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_turquise",
    category: "metal_material",
    name: "leather turquise",
    thumbnail: "/assets/thumbnails/leather_turquise.png",
    value: "/assets/metal_material/leather_turquise.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_turquoise_crocodile",
    category: "metal_material",
    name: "leather turquoise crocodile",
    thumbnail: "/assets/thumbnails/leather_turquoise_crocodile.png",
    value: "/assets/metal_material/leather_turquoise_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_violet_crocodile",
    category: "metal_material",
    name: "leather violet crocodile",
    thumbnail: "/assets/thumbnails/leather_violet_crocodile.png",
    value: "/assets/metal_material/leather_violet_crocodile.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_violet_snake",
    category: "metal_material",
    name: "leather violet snake",
    thumbnail: "/assets/thumbnails/leather_violet_snake.png",
    value: "/assets/metal_material/leather_violet_snake.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_white_snake",
    category: "metal_material",
    name: "leather white snake",
    thumbnail: "/assets/thumbnails/leather_white_snake.png",
    value: "/assets/metal_material/leather_white_snake.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_yellow_snake",
    category: "metal_material",
    name: "leather yellow snake",
    thumbnail: "/assets/thumbnails/leather_yellow_snake.png",
    value: "/assets/metal_material/leather_yellow_snake.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "ather_yellow",
    category: "metal_material",
    name: "leather yellow",
    thumbnail: "/assets/thumbnails/leather_yellow.png",
    value: "/assets/metal_material/leather_yellow.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "rble_black_1",
    category: "metal_material",
    name: "marble black 1",
    thumbnail: "/assets/thumbnails/marble_black_1.png",
    value: "/assets/metal_material/marble_black_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "rble_black_2",
    category: "metal_material",
    name: "marble black 2",
    thumbnail: "/assets/thumbnails/marble_black_2.png",
    value: "/assets/metal_material/marble_black_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "rble_white_1",
    category: "metal_material",
    name: "marble white 1",
    thumbnail: "/assets/thumbnails/marble_white_1.png",
    value: "/assets/metal_material/marble_white_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "rble_white_2",
    category: "metal_material",
    name: "marble white 2",
    thumbnail: "/assets/thumbnails/marble_white_2.png",
    value: "/assets/metal_material/marble_white_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "terial_1",
    category: "metal_material",
    name: "material 1",
    thumbnail: "/assets/thumbnails/material_1.png",
    value: "/assets/metal_material/material_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "terial_2",
    category: "metal_material",
    name: "material 2",
    thumbnail: "/assets/thumbnails/material_2.png",
    value: "/assets/metal_material/material_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "terial_3",
    category: "metal_material",
    name: "material 3",
    thumbnail: "/assets/thumbnails/material_3.png",
    value: "/assets/metal_material/material_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "terial_4",
    category: "metal_material",
    name: "material 4",
    thumbnail: "/assets/thumbnails/material_4.png",
    value: "/assets/metal_material/material_4.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "terial_5",
    category: "metal_material",
    name: "material 5",
    thumbnail: "/assets/thumbnails/material_5.png",
    value: "/assets/metal_material/material_5.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "terial_6",
    category: "metal_material",
    name: "material 6",
    thumbnail: "/assets/thumbnails/material_6.png",
    value: "/assets/metal_material/material_6.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "terial_horn_1",
    category: "metal_material",
    name: "material horn 1",
    thumbnail: "/assets/thumbnails/material_horn_1.png",
    value: "/assets/metal_material/material_horn_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_aluminum",
    category: "metal_material",
    name: "metal aluminum",
    thumbnail: "/assets/thumbnails/metal_aluminum.png",
    value: "/assets/metal_material/metal_aluminum.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_black_matt",
    category: "metal_material",
    name: "metal black matt",
    thumbnail: "/assets/thumbnails/metal_black_matt.png",
    value: "/assets/metal_material/metal_black_matt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_black_polished",
    category: "metal_material",
    name: "metal black polished",
    thumbnail: "/assets/thumbnails/metal_black_polished.png",
    value: "/assets/metal_material/metal_black_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_blue_matt",
    category: "metal_material",
    name: "metal blue matt",
    thumbnail: "/assets/thumbnails/metal_blue_matt.png",
    value: "/assets/metal_material/metal_blue_matt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_blue_polished_1",
    category: "metal_material",
    name: "metal blue polished 1",
    thumbnail: "/assets/thumbnails/metal_blue_polished_1.png",
    value: "/assets/metal_material/metal_blue_polished_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_blue_polished_2",
    category: "metal_material",
    name: "metal blue polished 2",
    thumbnail: "/assets/thumbnails/metal_blue_polished_2.png",
    value: "/assets/metal_material/metal_blue_polished_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_blue_polished_3",
    category: "metal_material",
    name: "metal blue polished 3",
    thumbnail: "/assets/thumbnails/metal_blue_polished_3.png",
    value: "/assets/metal_material/metal_blue_polished_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_blue_polished_4",
    category: "metal_material",
    name: "metal blue polished 4",
    thumbnail: "/assets/thumbnails/metal_blue_polished_4.png",
    value: "/assets/metal_material/metal_blue_polished_4.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_brass",
    category: "metal_material",
    name: "metal brass",
    thumbnail: "/assets/thumbnails/metal_brass.png",
    value: "/assets/metal_material/metal_brass.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_bronze",
    category: "metal_material",
    name: "metal bronze",
    thumbnail: "/assets/thumbnails/metal_bronze.png",
    value: "/assets/metal_material/metal_bronze.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_brown_matt",
    category: "metal_material",
    name: "metal brown matt",
    thumbnail: "/assets/thumbnails/metal_brown_matt.png",
    value: "/assets/metal_material/metal_brown_matt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_brown_polished",
    category: "metal_material",
    name: "metal brown polished",
    thumbnail: "/assets/thumbnails/metal_brown_polished.png",
    value: "/assets/metal_material/metal_brown_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_chrome",
    category: "metal_material",
    name: "metal chrome",
    thumbnail: "/assets/thumbnails/metal_chrome.png",
    value: "/assets/metal_material/metal_chrome.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_circles",
    category: "metal_material",
    name: "metal circles",
    thumbnail: "/assets/thumbnails/metal_circles.png",
    value: "/assets/metal_material/metal_circles.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_copper_1",
    category: "metal_material",
    name: "metal copper 1",
    thumbnail: "/assets/thumbnails/metal_copper_1.png",
    value: "/assets/metal_material/metal_copper_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_copper_2",
    category: "metal_material",
    name: "metal copper 2",
    thumbnail: "/assets/thumbnails/metal_copper_2.png",
    value: "/assets/metal_material/metal_copper_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_copper_3",
    category: "metal_material",
    name: "metal copper 3",
    thumbnail: "/assets/thumbnails/metal_copper_3.png",
    value: "/assets/metal_material/metal_copper_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_copper_4",
    category: "metal_material",
    name: "metal copper 4",
    thumbnail: "/assets/thumbnails/metal_copper_4.png",
    value: "/assets/metal_material/metal_copper_4.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_1",
    category: "metal_material",
    name: "metal gold texture 1",
    thumbnail: "/assets/thumbnails/metal_gold_texture_1.png",
    value: "/assets/metal_material/metal_gold_texture_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_2",
    category: "metal_material",
    name: "metal gold texture 2",
    thumbnail: "/assets/thumbnails/metal_gold_texture_2.png",
    value: "/assets/metal_material/metal_gold_texture_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_3",
    category: "metal_material",
    name: "metal gold texture 3",
    thumbnail: "/assets/thumbnails/metal_gold_texture_3.png",
    value: "/assets/metal_material/metal_gold_texture_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_4",
    category: "metal_material",
    name: "metal gold texture 4",
    thumbnail: "/assets/thumbnails/metal_gold_texture_4.png",
    value: "/assets/metal_material/metal_gold_texture_4.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_5",
    category: "metal_material",
    name: "metal gold texture 5",
    thumbnail: "/assets/thumbnails/metal_gold_texture_5.png",
    value: "/assets/metal_material/metal_gold_texture_5.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_6",
    category: "metal_material",
    name: "metal gold texture 6",
    thumbnail: "/assets/thumbnails/metal_gold_texture_6.png",
    value: "/assets/metal_material/metal_gold_texture_6.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_7",
    category: "metal_material",
    name: "metal gold texture 7",
    thumbnail: "/assets/thumbnails/metal_gold_texture_7.png",
    value: "/assets/metal_material/metal_gold_texture_7.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_8",
    category: "metal_material",
    name: "metal gold texture 8",
    thumbnail: "/assets/thumbnails/metal_gold_texture_8.png",
    value: "/assets/metal_material/metal_gold_texture_8.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_gold_texture_9",
    category: "metal_material",
    name: "metal gold texture 9",
    thumbnail: "/assets/thumbnails/metal_gold_texture_9.png",
    value: "/assets/metal_material/metal_gold_texture_9.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_green_polished_1",
    category: "metal_material",
    name: "metal green polished 1",
    thumbnail: "/assets/thumbnails/metal_green_polished_1.png",
    value: "/assets/metal_material/metal_green_polished_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_green_polished_2",
    category: "metal_material",
    name: "metal green polished 2",
    thumbnail: "/assets/thumbnails/metal_green_polished_2.png",
    value: "/assets/metal_material/metal_green_polished_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_grey_polished",
    category: "metal_material",
    name: "metal grey polished",
    thumbnail: "/assets/thumbnails/metal_grey_polished.png",
    value: "/assets/metal_material/metal_grey_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_meteorit",
    category: "metal_material",
    name: "metal meteorit",
    thumbnail: "/assets/thumbnails/metal_meteorit.png",
    value: "/assets/metal_material/metal_meteorit.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_patina",
    category: "metal_material",
    name: "metal patina",
    thumbnail: "/assets/thumbnails/metal_patina.png",
    value: "/assets/metal_material/metal_patina.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_purple_polished",
    category: "metal_material",
    name: "metal purple polished",
    thumbnail: "/assets/thumbnails/metal_purple_polished.png",
    value: "/assets/metal_material/metal_purple_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_red_matt",
    category: "metal_material",
    name: "metal red matt",
    thumbnail: "/assets/thumbnails/metal_red_matt.png",
    value: "/assets/metal_material/metal_red_matt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_red_polished_1",
    category: "metal_material",
    name: "metal red polished 1",
    thumbnail: "/assets/thumbnails/metal_red_polished_1.png",
    value: "/assets/metal_material/metal_red_polished_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_brass",
    category: "metal_material",
    name: "metal rosegold brass",
    thumbnail: "/assets/thumbnails/metal_rosegold_brass.png",
    value: "/assets/metal_material/metal_rosegold_brass.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_brush_1",
    category: "metal_material",
    name: "metal rosegold brush 1",
    thumbnail: "/assets/thumbnails/metal_rosegold_brush_1.png",
    value: "/assets/metal_material/metal_rosegold_brush_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_brush_2",
    category: "metal_material",
    name: "metal rosegold brush 2",
    thumbnail: "/assets/thumbnails/metal_rosegold_brush_2.png",
    value: "/assets/metal_material/metal_rosegold_brush_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_brush_3",
    category: "metal_material",
    name: "metal rosegold brush 3",
    thumbnail: "/assets/thumbnails/metal_rosegold_brush_3.png",
    value: "/assets/metal_material/metal_rosegold_brush_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_hammer",
    category: "metal_material",
    name: "metal rosegold hammer",
    thumbnail: "/assets/thumbnails/metal_rosegold_hammer.png",
    value: "/assets/metal_material/metal_rosegold_hammer.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_hammeredlinear",
    category: "metal_material",
    name: "metal rosegold hammeredlinear",
    thumbnail: "/assets/thumbnails/metal_rosegold_hammeredlinear.png",
    value: "/assets/metal_material/metal_rosegold_hammeredlinear.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_hammeredwave",
    category: "metal_material",
    name: "metal rosegold hammeredwave",
    thumbnail: "/assets/thumbnails/metal_rosegold_hammeredwave.png",
    value: "/assets/metal_material/metal_rosegold_hammeredwave.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_lightscratch",
    category: "metal_material",
    name: "metal rosegold lightscratch",
    thumbnail: "/assets/thumbnails/metal_rosegold_lightscratch.png",
    value: "/assets/metal_material/metal_rosegold_lightscratch.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_matt",
    category: "metal_material",
    name: "metal rosegold matt",
    thumbnail: "/assets/thumbnails/metal_rosegold_matt.png",
    value: "/assets/metal_material/metal_rosegold_matt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_oxidized",
    category: "metal_material",
    name: "metal rosegold oxidized",
    thumbnail: "/assets/thumbnails/metal_rosegold_oxidized.png",
    value: "/assets/metal_material/metal_rosegold_oxidized.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_polished_2",
    category: "metal_material",
    name: "metal rosegold polished 2",
    thumbnail: "/assets/thumbnails/metal_rosegold_polished_2.png",
    value: "/assets/metal_material/metal_rosegold_polished_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_sand",
    category: "metal_material",
    name: "metal rosegold sand",
    thumbnail: "/assets/thumbnails/metal_rosegold_sand.png",
    value: "/assets/metal_material/metal_rosegold_sand.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_scratch",
    category: "metal_material",
    name: "metal rosegold scratch",
    thumbnail: "/assets/thumbnails/metal_rosegold_scratch.png",
    value: "/assets/metal_material/metal_rosegold_scratch.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_rosegold_sparkle",
    category: "metal_material",
    name: "metal rosegold sparkle",
    thumbnail: "/assets/thumbnails/metal_rosegold_sparkle.png",
    value: "/assets/metal_material/metal_rosegold_sparkle.pmat",
    userId: null,
    weight: 10,
  },

  {
    type: "tal_rosegold_sparklelight",
    category: "metal_material",
    name: "metal rosegold sparklelight",
    thumbnail: "/assets/thumbnails/metal_rosegold_sparklelight.png",
    value: "/assets/metal_material/metal_rosegold_sparklelight.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_violet_polished",
    category: "metal_material",
    name: "metal violet polished",
    thumbnail: "/assets/thumbnails/metal_violet_polished.png",
    value: "/assets/metal_material/metal_violet_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_white_enamel",
    category: "metal_material",
    name: "metal white enamel",
    thumbnail: "/assets/thumbnails/metal_white_enamel.png",
    value: "/assets/metal_material/metal_white_enamel.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_white_polished",
    category: "metal_material",
    name: "metal white polished",
    thumbnail: "/assets/thumbnails/metal_white_polished.png",
    value: "/assets/metal_material/metal_white_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_brush_1",
    category: "metal_material",
    name: "metal whitegold brush 1",
    thumbnail: "/assets/thumbnails/metal_whitegold_brush_1.png",
    value: "/assets/metal_material/metal_whitegold_brush_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_brush_2",
    category: "metal_material",
    name: "metal whitegold brush 2",
    thumbnail: "/assets/thumbnails/metal_whitegold_brush_2.png",
    value: "/assets/metal_material/metal_whitegold_brush_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_brush_3",
    category: "metal_material",
    name: "metal whitegold brush 3",
    thumbnail: "/assets/thumbnails/metal_whitegold_brush_3.png",
    value: "/assets/metal_material/metal_whitegold_brush_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_hammer",
    category: "metal_material",
    name: "metal whitegold hammer",
    thumbnail: "/assets/thumbnails/metal_whitegold_hammer.png",
    value: "/assets/metal_material/metal_whitegold_hammer.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_hammeredlinear",
    category: "metal_material",
    name: "metal whitegold hammeredlinear",
    thumbnail: "/assets/thumbnails/metal_whitegold_hammeredlinear.png",
    value: "/assets/metal_material/metal_whitegold_hammeredlinear.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_hammeredwave",
    category: "metal_material",
    name: "metal whitegold hammeredwave",
    thumbnail: "/assets/thumbnails/metal_whitegold_hammeredwave.png",
    value: "/assets/metal_material/metal_whitegold_hammeredwave.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_lightscratch",
    category: "metal_material",
    name: "metal whitegold lightscratch",
    thumbnail: "/assets/thumbnails/metal_whitegold_lightscratch.png",
    value: "/assets/metal_material/metal_whitegold_lightscratch.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_matt",
    category: "metal_material",
    name: "metal whitegold matt",
    thumbnail: "/assets/thumbnails/metal_whitegold_matt.png",
    value: "/assets/metal_material/metal_whitegold_matt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_oxidized",
    category: "metal_material",
    name: "metal whitegold oxidized",
    thumbnail: "/assets/thumbnails/metal_whitegold_oxidized.png",
    value: "/assets/metal_material/metal_whitegold_oxidized.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_sand",
    category: "metal_material",
    name: "metal whitegold sand",
    thumbnail: "/assets/thumbnails/metal_whitegold_sand.png",
    value: "/assets/metal_material/metal_whitegold_sand.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_scratch",
    category: "metal_material",
    name: "metal whitegold scratch",
    thumbnail: "/assets/thumbnails/metal_whitegold_scratch.png",
    value: "/assets/metal_material/metal_whitegold_scratch.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_sparkle",
    category: "metal_material",
    name: "metal whitegold sparkle",
    thumbnail: "/assets/thumbnails/metal_whitegold_sparkle.png",
    value: "/assets/metal_material/metal_whitegold_sparkle.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_whitegold_sparklelight",
    category: "metal_material",
    name: "metal whitegold sparklelight",
    thumbnail: "/assets/thumbnails/metal_whitegold_sparklelight.png",
    value: "/assets/metal_material/metal_whitegold_sparklelight.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_brass",
    category: "metal_material",
    name: "metal yellowgold brass",
    thumbnail: "/assets/thumbnails/metal_yellowgold_brass.png",
    value: "/assets/metal_material/metal_yellowgold_brass.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_brush_1",
    category: "metal_material",
    name: "metal yellowgold brush 1",
    thumbnail: "/assets/thumbnails/metal_yellowgold_brush_1.png",
    value: "/assets/metal_material/metal_yellowgold_brush_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_brush_2",
    category: "metal_material",
    name: "metal yellowgold brush 2",
    thumbnail: "/assets/thumbnails/metal_yellowgold_brush_2.png",
    value: "/assets/metal_material/metal_yellowgold_brush_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_brush_3",
    category: "metal_material",
    name: "metal yellowgold brush 3",
    thumbnail: "/assets/thumbnails/metal_yellowgold_brush_3.png",
    value: "/assets/metal_material/metal_yellowgold_brush_3.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_hammer",
    category: "metal_material",
    name: "metal yellowgold hammer",
    thumbnail: "/assets/thumbnails/metal_yellowgold_hammer.png",
    value: "/assets/metal_material/metal_yellowgold_hammer.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_hammeredlinear",
    category: "metal_material",
    name: "metal yellowgold hammeredlinear",
    thumbnail: "/assets/thumbnails/metal_yellowgold_hammeredlinear.png",
    value: "/assets/metal_material/metal_yellowgold_hammeredlinear.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_hammeredwave",
    category: "metal_material",
    name: "metal yellowgold hammeredwave",
    thumbnail: "/assets/thumbnails/metal_yellowgold_hammeredwave.png",
    value: "/assets/metal_material/metal_yellowgold_hammeredwave.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_lightscratch",
    category: "metal_material",
    name: "metal yellowgold lightscratch",
    thumbnail: "/assets/thumbnails/metal_yellowgold_lightscratch.png",
    value: "/assets/metal_material/metal_yellowgold_lightscratch.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_matt",
    category: "metal_material",
    name: "metal yellowgold matt",
    thumbnail: "/assets/thumbnails/metal_yellowgold_matt.png",
    value: "/assets/metal_material/metal_yellowgold_matt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_oxidized",
    category: "metal_material",
    name: "metal yellowgold oxidized",
    thumbnail: "/assets/thumbnails/metal_yellowgold_oxidized.png",
    value: "/assets/metal_material/metal_yellowgold_oxidized.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_polished",
    category: "metal_material",
    name: "metal yellowgold polished",
    thumbnail: "/assets/thumbnails/metal_yellowgold_polished.png",
    value: "/assets/metal_material/metal_yellowgold_polished.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_sand",
    category: "metal_material",
    name: "metal yellowgold sand",
    thumbnail: "/assets/thumbnails/metal_yellowgold_sand.png",
    value: "/assets/metal_material/metal_yellowgold_sand.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_scratch",
    category: "metal_material",
    name: "metal yellowgold scratch",
    thumbnail: "/assets/thumbnails/metal_yellowgold_scratch.png",
    value: "/assets/metal_material/metal_yellowgold_scratch.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_sparkle",
    category: "metal_material",
    name: "metal yellowgold sparkle",
    thumbnail: "/assets/thumbnails/metal_yellowgold_sparkle.png",
    value: "/assets/metal_material/metal_yellowgold_sparkle.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "tal_yellowgold_sparklelight",
    category: "metal_material",
    name: "metal yellowgold sparklelight",
    thumbnail: "/assets/thumbnails/metal_yellowgold_sparklelight.png",
    value: "/assets/metal_material/metal_yellowgold_sparklelight.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_black",
    category: "metal_material",
    name: "paper black",
    thumbnail: "/assets/thumbnails/paper_black.png",
    value: "/assets/metal_material/paper_black.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_blue_1",
    category: "metal_material",
    name: "paper blue 1",
    thumbnail: "/assets/thumbnails/paper_blue_1.png",
    value: "/assets/metal_material/paper_blue_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_blue_2",
    category: "metal_material",
    name: "paper blue 2",
    thumbnail: "/assets/thumbnails/paper_blue_2.png",
    value: "/assets/metal_material/paper_blue_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_green_1",
    category: "metal_material",
    name: "paper green 1",
    thumbnail: "/assets/thumbnails/paper_green_1.png",
    value: "/assets/metal_material/paper_green_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_peach",
    category: "metal_material",
    name: "paper peach",
    thumbnail: "/assets/thumbnails/paper_peach.png",
    value: "/assets/metal_material/paper_peach.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_red_1",
    category: "metal_material",
    name: "paper red 1",
    thumbnail: "/assets/thumbnails/paper_red_1.png",
    value: "/assets/metal_material/paper_red_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_red_2",
    category: "metal_material",
    name: "paper red 2",
    thumbnail: "/assets/thumbnails/paper_red_2.png",
    value: "/assets/metal_material/paper_red_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_turquoise",
    category: "metal_material",
    name: "paper turquoise",
    thumbnail: "/assets/thumbnails/paper_turquoise.png",
    value: "/assets/metal_material/paper_turquoise.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per_white",
    category: "metal_material",
    name: "paper white",
    thumbnail: "/assets/thumbnails/paper_white.png",
    value: "/assets/metal_material/paper_white.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "per",
    category: "metal_material",
    name: "paper",
    thumbnail: "/assets/thumbnails/paper.png",
    value: "/assets/metal_material/paper.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_blue_pearlmutt",
    category: "metal_material",
    name: "pearl blue pearlmutt",
    thumbnail: "/assets/thumbnails/pearl_blue_pearlmutt.png",
    value: "/assets/metal_material/pearl_blue_pearlmutt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_gold_1",
    category: "metal_material",
    name: "pearl gold 1",
    thumbnail: "/assets/thumbnails/pearl_gold_1.png",
    value: "/assets/metal_material/pearl_gold_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_gold_2",
    category: "metal_material",
    name: "pearl gold 2",
    thumbnail: "/assets/thumbnails/pearl_gold_2.png",
    value: "/assets/metal_material/pearl_gold_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_grey_light",
    category: "metal_material",
    name: "pearl grey light",
    thumbnail: "/assets/thumbnails/pearl_grey_light.png",
    value: "/assets/metal_material/pearl_grey_light.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_grey",
    category: "metal_material",
    name: "pearl grey",
    thumbnail: "/assets/thumbnails/pearl_grey.png",
    value: "/assets/metal_material/pearl_grey.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_peach",
    category: "metal_material",
    name: "pearl peach",
    thumbnail: "/assets/thumbnails/pearl_peach.png",
    value: "/assets/metal_material/pearl_peach.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_pink_light",
    category: "metal_material",
    name: "pearl pink light",
    thumbnail: "/assets/thumbnails/pearl_pink_light.png",
    value: "/assets/metal_material/pearl_pink_light.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_rose_1",
    category: "metal_material",
    name: "pearl rose 1",
    thumbnail: "/assets/thumbnails/pearl_rose_1.png",
    value: "/assets/metal_material/pearl_rose_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_rose_2",
    category: "metal_material",
    name: "pearl rose 2",
    thumbnail: "/assets/thumbnails/pearl_rose_2.png",
    value: "/assets/metal_material/pearl_rose_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_tahity_1",
    category: "metal_material",
    name: "pearl tahity 1",
    thumbnail: "/assets/thumbnails/pearl_tahity_1.png",
    value: "/assets/metal_material/pearl_tahity_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_tahity_2",
    category: "metal_material",
    name: "pearl tahity 2",
    thumbnail: "/assets/thumbnails/pearl_tahity_2.png",
    value: "/assets/metal_material/pearl_tahity_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_white_1",
    category: "metal_material",
    name: "pearl white 1",
    thumbnail: "/assets/thumbnails/pearl_white_1.png",
    value: "/assets/metal_material/pearl_white_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arl_white_2",
    category: "metal_material",
    name: "pearl white 2",
    thumbnail: "/assets/thumbnails/pearl_white_2.png",
    value: "/assets/metal_material/pearl_white_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "arlmutt",
    category: "metal_material",
    name: "pearlmutt",
    thumbnail: "/assets/thumbnails/pearlmutt.png",
    value: "/assets/metal_material/pearlmutt.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_black",
    category: "metal_material",
    name: "plastic black",
    thumbnail: "/assets/thumbnails/plastic_black.png",
    value: "/assets/metal_material/plastic_black.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_blue_dark",
    category: "metal_material",
    name: "plastic blue dark",
    thumbnail: "/assets/thumbnails/plastic_blue_dark.png",
    value: "/assets/metal_material/plastic_blue_dark.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_blue_indigo",
    category: "metal_material",
    name: "plastic blue indigo",
    thumbnail: "/assets/thumbnails/plastic_blue_indigo.png",
    value: "/assets/metal_material/plastic_blue_indigo.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_blue_light",
    category: "metal_material",
    name: "plastic blue light",
    thumbnail: "/assets/thumbnails/plastic_blue_light.png",
    value: "/assets/metal_material/plastic_blue_light.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_blue",
    category: "metal_material",
    name: "plastic blue",
    thumbnail: "/assets/thumbnails/plastic_blue.png",
    value: "/assets/metal_material/plastic_blue.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_green_lime",
    category: "metal_material",
    name: "plastic green lime",
    thumbnail: "/assets/thumbnails/plastic_green_lime.png",
    value: "/assets/metal_material/plastic_green_lime.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_green",
    category: "metal_material",
    name: "plastic green",
    thumbnail: "/assets/thumbnails/plastic_green.png",
    value: "/assets/metal_material/plastic_green.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_grey",
    category: "metal_material",
    name: "plastic grey",
    thumbnail: "/assets/thumbnails/plastic_grey.png",
    value: "/assets/metal_material/plastic_grey.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_orange",
    category: "metal_material",
    name: "plastic orange",
    thumbnail: "/assets/thumbnails/plastic_orange.png",
    value: "/assets/metal_material/plastic_orange.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_pink_dark",
    category: "metal_material",
    name: "plastic pink dark",
    thumbnail: "/assets/thumbnails/plastic_pink_dark.png",
    value: "/assets/metal_material/plastic_pink_dark.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_pink_intense",
    category: "metal_material",
    name: "plastic pink intense",
    thumbnail: "/assets/thumbnails/plastic_pink_intense.png",
    value: "/assets/metal_material/plastic_pink_intense.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_pink_light",
    category: "metal_material",
    name: "plastic pink light",
    thumbnail: "/assets/thumbnails/plastic_pink_light.png",
    value: "/assets/metal_material/plastic_pink_light.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_pink",
    category: "metal_material",
    name: "plastic pink",
    thumbnail: "/assets/thumbnails/plastic_pink.png",
    value: "/assets/metal_material/plastic_pink.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_purple_light",
    category: "metal_material",
    name: "plastic purple light",
    thumbnail: "/assets/thumbnails/plastic_purple_light.png",
    value: "/assets/metal_material/plastic_purple_light.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_purple",
    category: "metal_material",
    name: "plastic purple",
    thumbnail: "/assets/thumbnails/plastic_purple.png",
    value: "/assets/metal_material/plastic_purple.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_red_1",
    category: "metal_material",
    name: "plastic red 1",
    thumbnail: "/assets/thumbnails/plastic_red_1.png",
    value: "/assets/metal_material/plastic_red_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_red_2",
    category: "metal_material",
    name: "plastic red 2",
    thumbnail: "/assets/thumbnails/plastic_red_2.png",
    value: "/assets/metal_material/plastic_red_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_rose",
    category: "metal_material",
    name: "plastic rose",
    thumbnail: "/assets/thumbnails/plastic_rose.png",
    value: "/assets/metal_material/plastic_rose.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_turquoise",
    category: "metal_material",
    name: "plastic turquoise",
    thumbnail: "/assets/thumbnails/plastic_turquoise.png",
    value: "/assets/metal_material/plastic_turquoise.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_violet_dark",
    category: "metal_material",
    name: "plastic violet dark",
    thumbnail: "/assets/thumbnails/plastic_violet_dark.png",
    value: "/assets/metal_material/plastic_violet_dark.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_violet_light",
    category: "metal_material",
    name: "plastic violet light",
    thumbnail: "/assets/thumbnails/plastic_violet_light.png",
    value: "/assets/metal_material/plastic_violet_light.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_violet",
    category: "metal_material",
    name: "plastic violet",
    thumbnail: "/assets/thumbnails/plastic_violet.png",
    value: "/assets/metal_material/plastic_violet.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_white",
    category: "metal_material",
    name: "plastic white",
    thumbnail: "/assets/thumbnails/plastic_white.png",
    value: "/assets/metal_material/plastic_white.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_yellow_light",
    category: "metal_material",
    name: "plastic yellow light",
    thumbnail: "/assets/thumbnails/plastic_yellow_light.png",
    value: "/assets/metal_material/plastic_yellow_light.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "astic_yellow",
    category: "metal_material",
    name: "plastic yellow",
    thumbnail: "/assets/thumbnails/plastic_yellow.png",
    value: "/assets/metal_material/plastic_yellow.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_brown_light",
    category: "metal_material",
    name: "wood brown light",
    thumbnail: "/assets/thumbnails/wood_brown_light.png",
    value: "/assets/metal_material/wood_brown_light.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_brown",
    category: "metal_material",
    name: "wood brown",
    thumbnail: "/assets/thumbnails/wood_brown.png",
    value: "/assets/metal_material/wood_brown.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_cork",
    category: "metal_material",
    name: "wood cork",
    thumbnail: "/assets/thumbnails/wood_cork.png",
    value: "/assets/metal_material/wood_cork.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_darkbrown_1",
    category: "metal_material",
    name: "wood darkbrown 1",
    thumbnail: "/assets/thumbnails/wood_darkbrown_1.png",
    value: "/assets/metal_material/wood_darkbrown_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_darkbrown_2",
    category: "metal_material",
    name: "wood darkbrown 2",
    thumbnail: "/assets/thumbnails/wood_darkbrown_2.png",
    value: "/assets/metal_material/wood_darkbrown_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_ebony",
    category: "metal_material",
    name: "wood ebony",
    thumbnail: "/assets/thumbnails/wood_ebony.png",
    value: "/assets/metal_material/wood_ebony.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_goldbrown_1",
    category: "metal_material",
    name: "wood goldbrown 1",
    thumbnail: "/assets/thumbnails/wood_goldbrown_1.png",
    value: "/assets/metal_material/wood_goldbrown_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_goldbrown_2",
    category: "metal_material",
    name: "wood goldbrown 2",
    thumbnail: "/assets/thumbnails/wood_goldbrown_2.png",
    value: "/assets/metal_material/wood_goldbrown_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_grey",
    category: "metal_material",
    name: "wood grey",
    thumbnail: "/assets/thumbnails/wood_grey.png",
    value: "/assets/metal_material/wood_grey.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_red_1",
    category: "metal_material",
    name: "wood red 1",
    thumbnail: "/assets/thumbnails/wood_red_1.png",
    value: "/assets/metal_material/wood_red_1.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_red_2",
    category: "metal_material",
    name: "wood red 2",
    thumbnail: "/assets/thumbnails/wood_red_2.png",
    value: "/assets/metal_material/wood_red_2.pmat",
    userId: null,
    weight: 10,
  },
  {
    type: "od_red",
    category: "metal_material",
    name: "wood red",
    thumbnail: "/assets/thumbnails/wood_red.png",
    value: "/assets/metal_material/wood_red.pmat",
    userId: null,
    weight: 10,
  },
];
