export default [
  {
    type: "background",
    category: "background",
    name: "bg linear gray",
    thumbnail: "assets/thumbnails/bg_linear_gray.png",
    value: "assets/background/bg_linear_gray.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg none",
    thumbnail: "assets/thumbnails/bg_none.png",
    value: "assets/background/bg_none.png",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "1 bg white",
    thumbnail: "assets/thumbnails/1_bg_white.png",
    value: "assets/background/1_bg_white.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg black",
    thumbnail: "assets/thumbnails/bg_black.png",
    value: "assets/background/bg_black.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg bone",
    thumbnail: "assets/thumbnails/bg_bone.png",
    value: "assets/background/bg_bone.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg linear antrasit",
    thumbnail: "assets/thumbnails/bg_linear_antrasit.png",
    value: "assets/background/bg_linear_antrasit.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg linear beige",
    thumbnail: "assets/thumbnails/bg_linear_beige.png",
    value: "assets/background/bg_linear_beige.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg linear graywhite 2",
    thumbnail: "assets/thumbnails/bg_linear_graywhite_2.png",
    value: "assets/background/bg_linear_graywhite_2.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg linear graywhite",
    thumbnail: "assets/thumbnails/bg_linear_graywhite.png",
    value: "assets/background/bg_linear_graywhite.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg linear lightblue",
    thumbnail: "assets/thumbnails/bg_linear_lightblue.png",
    value: "assets/background/bg_linear_lightblue.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg linear pinkwhite",
    thumbnail: "assets/thumbnails/bg_linear_pinkwhite.png",
    value: "assets/background/bg_linear_pinkwhite.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg linear turquoisewhite",
    thumbnail: "assets/thumbnails/bg_linear_turquoisewhite.png",
    value: "assets/background/bg_linear_turquoisewhite.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg pastelyellow",
    thumbnail: "assets/thumbnails/bg_pastelyellow.png",
    value: "assets/background/bg_pastelyellow.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial antrasit",
    thumbnail: "assets/thumbnails/bg_radial_antrasit.png",
    value: "assets/background/bg_radial_antrasit.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial aqua",
    thumbnail: "assets/thumbnails/bg_radial_aqua.png",
    value: "assets/background/bg_radial_aqua.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial beige",
    thumbnail: "assets/thumbnails/bg_radial_beige.png",
    value: "assets/background/bg_radial_beige.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial black",
    thumbnail: "assets/thumbnails/bg_radial_black.png",
    value: "assets/background/bg_radial_black.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial blue",
    thumbnail: "assets/thumbnails/bg_radial_blue.png",
    value: "assets/background/bg_radial_blue.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial coral",
    thumbnail: "assets/thumbnails/bg_radial_coral.png",
    value: "assets/background/bg_radial_coral.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial darkblue",
    thumbnail: "assets/thumbnails/bg_radial_darkblue.png",
    value: "assets/background/bg_radial_darkblue.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial fuchsia",
    thumbnail: "assets/thumbnails/bg_radial_fuchsia.png",
    value: "assets/background/bg_radial_fuchsia.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial gray",
    thumbnail: "assets/thumbnails/bg_radial_gray.png",
    value: "assets/background/bg_radial_gray.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial green",
    thumbnail: "assets/thumbnails/bg_radial_green.png",
    value: "assets/background/bg_radial_green.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial grey",
    thumbnail: "assets/thumbnails/bg_radial_grey.png",
    value: "assets/background/bg_radial_grey.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial red",
    thumbnail: "assets/thumbnails/bg_radial_red.png",
    value: "assets/background/bg_radial_red.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial white",
    thumbnail: "assets/thumbnails/bg_radial_white.png",
    value: "assets/background/bg_radial_white.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg radial light blue",
    thumbnail: "assets/thumbnails/bg_radiallight_blue.png",
    value: "assets/background/bg_radiallight_blue.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg turquoise",
    thumbnail: "assets/thumbnails/bg_turquoise.png",
    value: "assets/background/bg_turquoise.svg",
    userId: null,
    weight: 10,
  },
  {
    type: "background",
    category: "background",
    name: "bg wine",
    thumbnail: "assets/thumbnails/bg_wine.png",
    value: "assets/background/bg_wine.svg",
    userId: null,
    weight: 10,
  },
];
