export default [
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 001",
    thumbnail: "assets/thumbnails/env_gem_001.png",
    value: "assets/gem_env/env_gem_001.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 002",
    thumbnail: "assets/thumbnails/env_gem_002.png",
    value: "assets/gem_env/env_gem_002.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 003",
    thumbnail: "assets/thumbnails/env_gem_003.png",
    value: "assets/gem_env/env_gem_003.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 004",
    thumbnail: "assets/thumbnails/env_gem_004.png",
    value: "assets/gem_env/env_gem_004.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 005",
    thumbnail: "assets/thumbnails/env_gem_005.png",
    value: "assets/gem_env/env_gem_005.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 006",
    thumbnail: "assets/thumbnails/env_gem_006.png",
    value: "assets/gem_env/env_gem_006.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 007 a",
    thumbnail: "assets/thumbnails/env_gem_007_a.png",
    value: "assets/gem_env/env_gem_007_a.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 007 b",
    thumbnail: "assets/thumbnails/env_gem_007_b.png",
    value: "assets/gem_env/env_gem_007_b.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 007 c",
    thumbnail: "assets/thumbnails/env_gem_007_c.png",
    value: "assets/gem_env/env_gem_007_c.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 010",
    thumbnail: "assets/thumbnails/env_gem_010.png",
    value: "assets/gem_env/env_gem_010.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 012",
    thumbnail: "assets/thumbnails/env_gem_012.png",
    value: "assets/gem_env/env_gem_012.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 013",
    thumbnail: "assets/thumbnails/env_gem_013.png",
    value: "assets/gem_env/env_gem_013.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 016",
    thumbnail: "assets/thumbnails/env_gem_016.png",
    value: "assets/gem_env/env_gem_016.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 018",
    thumbnail: "assets/thumbnails/env_gem_018.png",
    value: "assets/gem_env/env_gem_018.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 020",
    thumbnail: "assets/thumbnails/env_gem_020.png",
    value: "assets/gem_env/env_gem_020.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 021",
    thumbnail: "assets/thumbnails/env_gem_021.png",
    value: "assets/gem_env/env_gem_021.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 022",
    thumbnail: "assets/thumbnails/env_gem_022.png",
    value: "assets/gem_env/env_gem_022.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 023",
    thumbnail: "assets/thumbnails/env_gem_023.png",
    value: "assets/gem_env/env_gem_023.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "gem_env",
    category: "gem_env",
    name: "env gem 024",
    thumbnail: "assets/thumbnails/env_gem_024.png",
    value: "assets/gem_env/env_gem_024.exr",
    userId: null,
    weight: 10,
  },
];
