export default [
  {
    type: "ground",
    category: "ground",
    name: "ground none",
    thumbnail: "/assets/thumbnails/ground_none.png",
    value: "/assets/ground/ground_none.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground shadow backleft",
    thumbnail: "/assets/thumbnails/ground_shadow_backleft.png",
    value: "/assets/ground/ground_shadow_backleft.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground shadow backright",
    thumbnail: "/assets/thumbnails/ground_shadow_backright.png",
    value: "/assets/ground/ground_shadow_backright.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground shadow frontleft",
    thumbnail: "/assets/thumbnails/ground_shadow_frontleft.png",
    value: "/assets/ground/ground_shadow_frontleft.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground shadow frontright",
    thumbnail: "/assets/thumbnails/ground_shadow_frontright.png",
    value: "/assets/ground/ground_shadow_frontright.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground shadow reflection",
    thumbnail: "/assets/thumbnails/ground_shadow_reflection.png",
    value: "/assets/ground/ground_shadow_reflection.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground shadow top 1",
    thumbnail: "/assets/thumbnails/ground_shadow_top_1.png",
    value: "/assets/ground/ground_shadow_top_1.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground shadow top",
    thumbnail: "/assets/thumbnails/ground_shadow_top.png",
    value: "/assets/ground/ground_shadow_top.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground softshadow backleft",
    thumbnail: "/assets/thumbnails/ground_softshadow_backleft.png",
    value: "/assets/ground/ground_softshadow_backleft.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground softshadow backright",
    thumbnail: "/assets/thumbnails/ground_softshadow_backright.png",
    value: "/assets/ground/ground_softshadow_backright.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground softshadow frontleft",
    thumbnail: "/assets/thumbnails/ground_softshadow_frontleft.png",
    value: "/assets/ground/ground_softshadow_frontleft.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground softshadow frontright",
    thumbnail: "/assets/thumbnails/ground_softshadow_frontright.png",
    value: "/assets/ground/ground_softshadow_frontright.json",
    userId: null,
    weight: 10,
  },
  {
    type: "ground",
    category: "ground",
    name: "ground ssrreflection",
    thumbnail: "/assets/thumbnails/ground_ssrreflection.png",
    value: "/assets/ground/ground_ssrreflection.json",
    userId: null,
    weight: 10,
  },
];
