export default [
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 001",
    thumbnail: "assets/thumbnails/env_metal_001.png",
    value: "assets/metal_env/env_metal_001.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 002",
    thumbnail: "assets/thumbnails/env_metal_002.png",
    value: "assets/metal_env/env_metal_002.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 003",
    thumbnail: "assets/thumbnails/env_metal_003.png",
    value: "assets/metal_env/env_metal_003.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 004 a",
    thumbnail: "assets/thumbnails/env_metal_004_a.png",
    value: "assets/metal_env/env_metal_004_a.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 004 b",
    thumbnail: "assets/thumbnails/env_metal_004_b.png",
    value: "assets/metal_env/env_metal_004_b.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 005",
    thumbnail: "assets/thumbnails/env_metal_005.png",
    value: "assets/metal_env/env_metal_005.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 006",
    thumbnail: "assets/thumbnails/env_metal_006.png",
    value: "assets/metal_env/env_metal_006.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 007",
    thumbnail: "assets/thumbnails/env_metal_007.png",
    value: "assets/metal_env/env_metal_007.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 008",
    thumbnail: "assets/thumbnails/env_metal_008.png",
    value: "assets/metal_env/env_metal_008.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 009",
    thumbnail: "assets/thumbnails/env_metal_009.png",
    value: "assets/metal_env/env_metal_009.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 010",
    thumbnail: "assets/thumbnails/env_metal_010.png",
    value: "assets/metal_env/env_metal_010.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 011",
    thumbnail: "assets/thumbnails/env_metal_011.png",
    value: "assets/metal_env/env_metal_011.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 012",
    thumbnail: "assets/thumbnails/env_metal_012.png",
    value: "assets/metal_env/env_metal_012.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 013",
    thumbnail: "assets/thumbnails/env_metal_013.png",
    value: "assets/metal_env/env_metal_013.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 014",
    thumbnail: "assets/thumbnails/env_metal_014.png",
    value: "assets/metal_env/env_metal_014.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 015",
    thumbnail: "assets/thumbnails/env_metal_015.png",
    value: "assets/metal_env/env_metal_015.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 016",
    thumbnail: "assets/thumbnails/env_metal_016.png",
    value: "assets/metal_env/env_metal_016.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 017",
    thumbnail: "assets/thumbnails/env_metal_017.png",
    value: "assets/metal_env/env_metal_017.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 018",
    thumbnail: "assets/thumbnails/env_metal_018.png",
    value: "assets/metal_env/env_metal_018.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 019",
    thumbnail: "assets/thumbnails/env_metal_019.png",
    value: "assets/metal_env/env_metal_019.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 020",
    thumbnail: "assets/thumbnails/env_metal_020.png",
    value: "assets/metal_env/env_metal_020.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 021",
    thumbnail: "assets/thumbnails/env_metal_021.png",
    value: "assets/metal_env/env_metal_021.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 022",
    thumbnail: "assets/thumbnails/env_metal_022.png",
    value: "assets/metal_env/env_metal_022.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 023",
    thumbnail: "assets/thumbnails/env_metal_023.png",
    value: "assets/metal_env/env_metal_023.hdr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 024 a",
    thumbnail: "assets/thumbnails/env_metal_024_a.png",
    value: "assets/metal_env/env_metal_024_a.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 024 b",
    thumbnail: "assets/thumbnails/env_metal_024_b.png",
    value: "assets/metal_env/env_metal_024_b.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 025",
    thumbnail: "assets/thumbnails/env_metal_025.png",
    value: "assets/metal_env/env_metal_025.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 026",
    thumbnail: "assets/thumbnails/env_metal_026.png",
    value: "assets/metal_env/env_metal_026.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 027",
    thumbnail: "assets/thumbnails/env_metal_027.png",
    value: "assets/metal_env/env_metal_027.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 028",
    thumbnail: "assets/thumbnails/env_metal_028.png",
    value: "assets/metal_env/env_metal_028.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 029",
    thumbnail: "assets/thumbnails/env_metal_029.png",
    value: "assets/metal_env/env_metal_029.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 030",
    thumbnail: "assets/thumbnails/env_metal_030.png",
    value: "assets/metal_env/env_metal_030.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 031",
    thumbnail: "assets/thumbnails/env_metal_031.png",
    value: "assets/metal_env/env_metal_031.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 032",
    thumbnail: "assets/thumbnails/env_metal_032.png",
    value: "assets/metal_env/env_metal_032.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 033 a",
    thumbnail: "assets/thumbnails/env_metal_033_a.png",
    value: "assets/metal_env/env_metal_033_a.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 033 b",
    thumbnail: "assets/thumbnails/env_metal_033_b.png",
    value: "assets/metal_env/env_metal_033_b.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 034",
    thumbnail: "assets/thumbnails/env_metal_034.png",
    value: "assets/metal_env/env_metal_034.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 035",
    thumbnail: "assets/thumbnails/env_metal_035.png",
    value: "assets/metal_env/env_metal_035.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 036",
    thumbnail: "assets/thumbnails/env_metal_036.png",
    value: "assets/metal_env/env_metal_036.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 037",
    thumbnail: "assets/thumbnails/env_metal_037.png",
    value: "assets/metal_env/env_metal_037.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 038",
    thumbnail: "assets/thumbnails/env_metal_038.png",
    value: "assets/metal_env/env_metal_038.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 039",
    thumbnail: "assets/thumbnails/env_metal_039.png",
    value: "assets/metal_env/env_metal_039.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 040",
    thumbnail: "assets/thumbnails/env_metal_040.png",
    value: "assets/metal_env/env_metal_040.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 041",
    thumbnail: "assets/thumbnails/env_metal_041.png",
    value: "assets/metal_env/env_metal_041.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 042 a",
    thumbnail: "assets/thumbnails/env_metal_042_a.png",
    value: "assets/metal_env/env_metal_042_a.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 042 b",
    thumbnail: "assets/thumbnails/env_metal_042_b.png",
    value: "assets/metal_env/env_metal_042_b.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 043",
    thumbnail: "assets/thumbnails/env_metal_043.png",
    value: "assets/metal_env/env_metal_043.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 044 a",
    thumbnail: "assets/thumbnails/env_metal_044_a.png",
    value: "assets/metal_env/env_metal_044_a.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 044 b",
    thumbnail: "assets/thumbnails/env_metal_044_b.png",
    value: "assets/metal_env/env_metal_044_b.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 045",
    thumbnail: "assets/thumbnails/env_metal_045.png",
    value: "assets/metal_env/env_metal_045.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 046",
    thumbnail: "assets/thumbnails/env_metal_046.png",
    value: "assets/metal_env/env_metal_046.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 047",
    thumbnail: "assets/thumbnails/env_metal_047.png",
    value: "assets/metal_env/env_metal_047.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 048",
    thumbnail: "assets/thumbnails/env_metal_048.png",
    value: "assets/metal_env/env_metal_048.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 049",
    thumbnail: "assets/thumbnails/env_metal_049.png",
    value: "assets/metal_env/env_metal_049.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 050",
    thumbnail: "assets/thumbnails/env_metal_050.png",
    value: "assets/metal_env/env_metal_050.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 051",
    thumbnail: "assets/thumbnails/env_metal_051.png",
    value: "assets/metal_env/env_metal_051.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 052",
    thumbnail: "assets/thumbnails/env_metal_052.png",
    value: "assets/metal_env/env_metal_052.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 053",
    thumbnail: "assets/thumbnails/env_metal_053.png",
    value: "assets/metal_env/env_metal_053.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 054",
    thumbnail: "assets/thumbnails/env_metal_054.png",
    value: "assets/metal_env/env_metal_054.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 055",
    thumbnail: "assets/thumbnails/env_metal_055.png",
    value: "assets/metal_env/env_metal_055.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 056",
    thumbnail: "assets/thumbnails/env_metal_056.png",
    value: "assets/metal_env/env_metal_056.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 057",
    thumbnail: "assets/thumbnails/env_metal_057.png",
    value: "assets/metal_env/env_metal_057.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 058 a",
    thumbnail: "assets/thumbnails/env_metal_058_a.png",
    value: "assets/metal_env/env_metal_058_a.exr",
    userId: null,
    weight: 10,
  },
  {
    type: "metal_env",
    category: "metal_env",
    name: "env metal 058 b",
    thumbnail: "assets/thumbnails/env_metal_058_b.png",
    value: "assets/metal_env/env_metal_058_b.exr",
    userId: null,
    weight: 10,
  },
];
