export default [
  {
    type: "scene",
    category: "scene",
    name: "ss 001",
    thumbnail: "assets/thumbnails/ss_001.png",
    value: "assets/scene/ss_001.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 002",
    thumbnail: "assets/thumbnails/ss_002.png",
    value: "assets/scene/ss_002.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 003",
    thumbnail: "assets/thumbnails/ss_003.png",
    value: "assets/scene/ss_003.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 004",
    thumbnail: "assets/thumbnails/ss_004.png",
    value: "assets/scene/ss_004.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 005",
    thumbnail: "assets/thumbnails/ss_005.png",
    value: "assets/scene/ss_005.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 006",
    thumbnail: "assets/thumbnails/ss_006.png",
    value: "assets/scene/ss_006.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 007",
    thumbnail: "assets/thumbnails/ss_007.png",
    value: "assets/scene/ss_007.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 008",
    thumbnail: "assets/thumbnails/ss_008.png",
    value: "assets/scene/ss_008.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 009",
    thumbnail: "assets/thumbnails/ss_009.png",
    value: "assets/scene/ss_009.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 010",
    thumbnail: "assets/thumbnails/ss_010.png",
    value: "assets/scene/ss_010.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 011",
    thumbnail: "assets/thumbnails/ss_011.png",
    value: "assets/scene/ss_011.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 012",
    thumbnail: "assets/thumbnails/ss_012.png",
    value: "assets/scene/ss_012.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 013",
    thumbnail: "assets/thumbnails/ss_013.png",
    value: "assets/scene/ss_013.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 014",
    thumbnail: "assets/thumbnails/ss_014.png",
    value: "assets/scene/ss_014.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 015",
    thumbnail: "assets/thumbnails/ss_015.png",
    value: "assets/scene/ss_015.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 016",
    thumbnail: "assets/thumbnails/ss_016.png",
    value: "assets/scene/ss_016.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 017",
    thumbnail: "assets/thumbnails/ss_017.png",
    value: "assets/scene/ss_017.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 018",
    thumbnail: "assets/thumbnails/ss_018.png",
    value: "assets/scene/ss_018.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 019",
    thumbnail: "assets/thumbnails/ss_019.png",
    value: "assets/scene/ss_019.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 020",
    thumbnail: "assets/thumbnails/ss_020.png",
    value: "assets/scene/ss_020.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 021",
    thumbnail: "assets/thumbnails/ss_021.png",
    value: "assets/scene/ss_021.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 022",
    thumbnail: "assets/thumbnails/ss_022.png",
    value: "assets/scene/ss_022.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 023",
    thumbnail: "assets/thumbnails/ss_023.png",
    value: "assets/scene/ss_023.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 024",
    thumbnail: "assets/thumbnails/ss_024.png",
    value: "assets/scene/ss_024.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 025",
    thumbnail: "assets/thumbnails/ss_025.png",
    value: "assets/scene/ss_025.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 026",
    thumbnail: "assets/thumbnails/ss_026.png",
    value: "assets/scene/ss_026.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 027 a",
    thumbnail: "assets/thumbnails/ss_027_a.png",
    value: "assets/scene/ss_027_a.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 027 b",
    thumbnail: "assets/thumbnails/ss_027_b.png",
    value: "assets/scene/ss_027_b.vjson",
    userId: null,
    weight: 10,
  },
  {
    type: "scene",
    category: "scene",
    name: "ss 027 c",
    thumbnail: "assets/thumbnails/ss_027_c.png",
    value: "assets/scene/ss_027_c.vjson",
    userId: null,
    weight: 10,
  },
];
