// Base catalog templates to be seeded into the database
// These are the default templates available to all users

export default [
  {
    templateId: "luxury-classic",
    name: "Luxury Classic",
    description:
      "Elegant jewelry catalog with premium serif fonts, gold accents, and sophisticated layouts designed for A4 edge-to-edge printing.",
    fontFamily: "Playfair Display",
    isBaseTemplate: true,
    userId: null,
    pages: [
      {
        backgroundColor: "#faf8f5",
        backgroundGradient: {
          from: "#faf8f5",
          to: "#f5f0e8",
          direction: "vertical",
        },
        elements: [
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 0,
            width: 794,
            height: 8,
            fill: "#d4af37",
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 1115,
            width: 794,
            height: 8,
            fill: "#d4af37",
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 40,
            y: 30,
            width: 80,
            height: 80,
            fill: "transparent",
            stroke: "#d4af37",
            strokeWidth: 3,
            zIndex: 2,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 674,
            y: 30,
            width: 80,
            height: 80,
            fill: "transparent",
            stroke: "#d4af37",
            strokeWidth: 3,
            zIndex: 2,
          },
          {
            type: "text",
            x: 97,
            y: 320,
            width: 600,
            height: 120,
            text: "LUXURY",
            fontSize: 96,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "center",
            fontWeight: "bold",
            zIndex: 4,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 247,
            y: 450,
            width: 300,
            height: 4,
            fill: "#d4af37",
            zIndex: 3,
          },
          {
            type: "text",
            x: 97,
            y: 480,
            width: 600,
            height: 60,
            text: "Jewelry Collection",
            fontSize: 38,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "center",
            fontWeight: "normal",
            fontStyle: "italic",
            zIndex: 4,
          },
          {
            type: "image",
            x: 297,
            y: 580,
            width: 200,
            height: 200,
            zIndex: 2,
          },
          {
            type: "shape",
            shapeType: "circle",
            x: 297,
            y: 580,
            width: 200,
            height: 200,
            fill: "transparent",
            stroke: "#d4af37",
            strokeWidth: 4,
            zIndex: 1,
          },
          {
            type: "text",
            x: 97,
            y: 840,
            width: 600,
            height: 50,
            text: "Crafted with Excellence, Worn with Pride",
            fontSize: 24,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "center",
            fontWeight: "normal",
            fontStyle: "italic",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 297,
            y: 820,
            width: 200,
            height: 2,
            fill: "#d4af37",
            zIndex: 2,
          },
          {
            type: "text",
            x: 97,
            y: 920,
            width: 600,
            height: 40,
            text: "2024 Collection",
            fontSize: 20,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "center",
            fontWeight: "normal",
            zIndex: 3,
          },
        ],
      },
      {
        backgroundColor: "#faf8f5",
        elements: [
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 0,
            width: 794,
            height: 120,
            fill: "#1a1a1a",
            zIndex: 1,
          },
          {
            type: "text",
            x: 97,
            y: 35,
            width: 600,
            height: 60,
            text: "FEATURED COLLECTION",
            fontSize: 44,
            fontFamily: "Playfair Display",
            color: "#faf8f5",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 247,
            y: 100,
            width: 300,
            height: 3,
            fill: "#d4af37",
            zIndex: 2,
          },
          {
            type: "image",
            x: 60,
            y: 160,
            width: 340,
            height: 340,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 60,
            y: 160,
            width: 340,
            height: 340,
            fill: "transparent",
            stroke: "#d4af37",
            strokeWidth: 3,
            zIndex: 2,
          },
          {
            type: "text",
            x: 60,
            y: 510,
            width: 340,
            height: 35,
            text: "Signature Diamond Ring",
            fontSize: 26,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 60,
            y: 555,
            width: 340,
            height: 32,
            text: "$2,499.00",
            fontSize: 28,
            fontFamily: "Playfair Display",
            color: "#d4af37",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "sku",
            x: 60,
            y: 595,
            width: 170,
            height: 22,
            text: "SKU: LUX-001",
            fontSize: 15,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "left",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "metalType",
            x: 230,
            y: 595,
            width: 170,
            height: 22,
            text: "18K White Gold",
            fontSize: 15,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "left",
            zIndex: 3,
          },
          {
            type: "image",
            x: 424,
            y: 160,
            width: 310,
            height: 310,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 424,
            y: 160,
            width: 310,
            height: 310,
            fill: "transparent",
            stroke: "#d4af37",
            strokeWidth: 3,
            zIndex: 2,
          },
          {
            type: "text",
            x: 424,
            y: 480,
            width: 310,
            height: 32,
            text: "Elegant Pearl Necklace",
            fontSize: 24,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 424,
            y: 520,
            width: 310,
            height: 30,
            text: "$1,899.00",
            fontSize: 26,
            fontFamily: "Playfair Display",
            color: "#d4af37",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "sku",
            x: 424,
            y: 558,
            width: 155,
            height: 22,
            text: "SKU: LUX-002",
            fontSize: 15,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "left",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "metalType",
            x: 579,
            y: 558,
            width: 155,
            height: 22,
            text: "Platinum",
            fontSize: 15,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "left",
            zIndex: 3,
          },
          {
            type: "image",
            x: 60,
            y: 650,
            width: 220,
            height: 220,
            zIndex: 1,
          },
          {
            type: "text",
            x: 60,
            y: 880,
            width: 220,
            height: 28,
            text: "Classic Earrings",
            fontSize: 18,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "center",
            fontWeight: "bold",
            zIndex: 2,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 60,
            y: 915,
            width: 220,
            height: 24,
            text: "$799.00",
            fontSize: 20,
            fontFamily: "Playfair Display",
            color: "#d4af37",
            align: "center",
            fontWeight: "bold",
            zIndex: 2,
          },
          {
            type: "image",
            x: 297,
            y: 650,
            width: 220,
            height: 220,
            zIndex: 1,
          },
          {
            type: "text",
            x: 297,
            y: 880,
            width: 220,
            height: 28,
            text: "Diamond Bracelet",
            fontSize: 18,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "center",
            fontWeight: "bold",
            zIndex: 2,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 297,
            y: 915,
            width: 220,
            height: 24,
            text: "$1,699.00",
            fontSize: 20,
            fontFamily: "Playfair Display",
            color: "#d4af37",
            align: "center",
            fontWeight: "bold",
            zIndex: 2,
          },
          {
            type: "image",
            x: 534,
            y: 650,
            width: 220,
            height: 220,
            zIndex: 1,
          },
          {
            type: "text",
            x: 534,
            y: 880,
            width: 220,
            height: 28,
            text: "Pendant Set",
            fontSize: 18,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "center",
            fontWeight: "bold",
            zIndex: 2,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 534,
            y: 915,
            width: 220,
            height: 24,
            text: "$599.00",
            fontSize: 20,
            fontFamily: "Playfair Display",
            color: "#d4af37",
            align: "center",
            fontWeight: "bold",
            zIndex: 2,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 1115,
            width: 794,
            height: 8,
            fill: "#d4af37",
            zIndex: 1,
          },
        ],
      },
      {
        backgroundColor: "#faf8f5",
        backgroundGradient: {
          from: "#faf8f5",
          to: "#f5f0e8",
          direction: "vertical",
        },
        elements: [
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 0,
            width: 794,
            height: 8,
            fill: "#d4af37",
            zIndex: 1,
          },
          {
            type: "text",
            x: 97,
            y: 80,
            width: 600,
            height: 70,
            text: "Visit Our Showroom",
            fontSize: 56,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 247,
            y: 160,
            width: 300,
            height: 3,
            fill: "#d4af37",
            zIndex: 2,
          },
          {
            type: "image",
            x: 60,
            y: 200,
            width: 340,
            height: 400,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 60,
            y: 200,
            width: 340,
            height: 400,
            fill: "transparent",
            stroke: "#d4af37",
            strokeWidth: 3,
            zIndex: 2,
          },
          {
            type: "text",
            x: 424,
            y: 220,
            width: 310,
            height: 40,
            text: "Experience Luxury",
            fontSize: 32,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "description",
            x: 424,
            y: 280,
            width: 310,
            height: 200,
            text: "Step into our elegant showroom where timeless craftsmanship meets modern luxury. Our master jewelers are ready to guide you through our exclusive collections and create custom pieces that reflect your unique style.\n\nEach visit is a personalized experience, ensuring you find the perfect piece that celebrates your most precious moments.",
            fontSize: 16,
            fontFamily: "Playfair Display",
            color: "#5a5a5a",
            align: "left",
            fontWeight: "normal",
            fontStyle: "normal",
            zIndex: 3,
          },
          {
            type: "text",
            x: 424,
            y: 500,
            width: 310,
            height: 30,
            text: "Location",
            fontSize: 20,
            fontFamily: "Playfair Display",
            color: "#d4af37",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "text",
            x: 424,
            y: 540,
            width: 310,
            height: 25,
            text: "123 Luxury Boulevard",
            fontSize: 17,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "left",
            fontWeight: "normal",
            zIndex: 3,
          },
          {
            type: "text",
            x: 424,
            y: 570,
            width: 310,
            height: 25,
            text: "New York, NY 10001",
            fontSize: 17,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "left",
            fontWeight: "normal",
            zIndex: 3,
          },
          {
            type: "text",
            x: 424,
            y: 610,
            width: 310,
            height: 30,
            text: "Contact",
            fontSize: 20,
            fontFamily: "Playfair Display",
            color: "#d4af37",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "text",
            x: 424,
            y: 650,
            width: 310,
            height: 25,
            text: "Phone: (555) 123-4567",
            fontSize: 17,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "left",
            fontWeight: "normal",
            zIndex: 3,
          },
          {
            type: "text",
            x: 424,
            y: 680,
            width: 310,
            height: 25,
            text: "Email: contact@gemora.com",
            fontSize: 17,
            fontFamily: "Playfair Display",
            color: "#1a1a1a",
            align: "left",
            fontWeight: "normal",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 60,
            y: 640,
            width: 340,
            height: 2,
            fill: "#d4af37",
            zIndex: 2,
          },
          {
            type: "text",
            x: 97,
            y: 720,
            width: 600,
            height: 50,
            text: "We look forward to welcoming you",
            fontSize: 22,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "center",
            fontWeight: "normal",
            fontStyle: "italic",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 674,
            y: 80,
            width: 80,
            height: 80,
            fill: "transparent",
            stroke: "#d4af37",
            strokeWidth: 3,
            zIndex: 2,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 40,
            y: 1043,
            width: 80,
            height: 80,
            fill: "transparent",
            stroke: "#d4af37",
            strokeWidth: 3,
            zIndex: 2,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 1115,
            width: 794,
            height: 8,
            fill: "#d4af37",
            zIndex: 1,
          },
          {
            type: "text",
            x: 97,
            y: 1050,
            width: 600,
            height: 35,
            text: "www.gemorastudio.com | @gemorastudio",
            fontSize: 16,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "center",
            fontWeight: "normal",
            zIndex: 3,
          },
        ],
      },
    ],
  },
  {
    templateId: "modern-minimal",
    name: "Modern Minimal",
    description:
      "Clean, sophisticated design with bold typography, geometric elements, and spacious layouts optimized for A4 printing.",
    fontFamily: "Inter",
    isBaseTemplate: true,
    userId: null,
    pages: [
      {
        backgroundColor: "#ffffff",
        elements: [
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 0,
            width: 794,
            height: 12,
            fill: "#000000",
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 1111,
            width: 794,
            height: 12,
            fill: "#000000",
            zIndex: 1,
          },
          {
            type: "text",
            x: 97,
            y: 320,
            width: 600,
            height: 140,
            text: "MODERN",
            fontSize: 120,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "circle",
            x: 372,
            y: 480,
            width: 50,
            height: 50,
            fill: "#000000",
            zIndex: 2,
          },
          {
            type: "text",
            x: 97,
            y: 550,
            width: 600,
            height: 50,
            text: "Collection 2024",
            fontSize: 32,
            fontFamily: "Inter",
            color: "#666666",
            align: "center",
            fontWeight: "normal",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 297,
            y: 620,
            width: 200,
            height: 2,
            fill: "#000000",
            zIndex: 2,
          },
          {
            type: "image",
            x: 297,
            y: 680,
            width: 200,
            height: 200,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 297,
            y: 680,
            width: 200,
            height: 200,
            fill: "transparent",
            stroke: "#000000",
            strokeWidth: 3,
            zIndex: 2,
          },
        ],
      },
      {
        backgroundColor: "#ffffff",
        elements: [
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 0,
            width: 794,
            height: 100,
            fill: "#000000",
            zIndex: 1,
          },
          {
            type: "text",
            x: 97,
            y: 25,
            width: 600,
            height: 60,
            text: "PRODUCT SHOWCASE",
            fontSize: 38,
            fontFamily: "Inter",
            color: "#ffffff",
            align: "center",
            fontWeight: "bold",
            zIndex: 2,
          },
          {
            type: "image",
            x: 20,
            y: 130,
            width: 248,
            height: 248,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 20,
            y: 130,
            width: 248,
            height: 248,
            fill: "transparent",
            stroke: "#e0e0e0",
            strokeWidth: 2,
            zIndex: 2,
          },
          {
            type: "text",
            x: 20,
            y: 390,
            width: 248,
            height: 28,
            text: "Product Name",
            fontSize: 18,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 20,
            y: 425,
            width: 248,
            height: 26,
            text: "$299",
            fontSize: 22,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "sku",
            x: 20,
            y: 458,
            width: 248,
            height: 20,
            text: "SKU: MOD-001",
            fontSize: 13,
            fontFamily: "Inter",
            color: "#999999",
            align: "center",
            zIndex: 3,
          },
          {
            type: "image",
            x: 273,
            y: 130,
            width: 248,
            height: 248,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 273,
            y: 130,
            width: 248,
            height: 248,
            fill: "transparent",
            stroke: "#e0e0e0",
            strokeWidth: 2,
            zIndex: 2,
          },
          {
            type: "text",
            x: 273,
            y: 390,
            width: 248,
            height: 28,
            text: "Product Name",
            fontSize: 18,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 273,
            y: 425,
            width: 248,
            height: 26,
            text: "$449",
            fontSize: 22,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "sku",
            x: 273,
            y: 458,
            width: 248,
            height: 20,
            text: "SKU: MOD-002",
            fontSize: 13,
            fontFamily: "Inter",
            color: "#999999",
            align: "center",
            zIndex: 3,
          },
          {
            type: "image",
            x: 526,
            y: 130,
            width: 248,
            height: 248,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 526,
            y: 130,
            width: 248,
            height: 248,
            fill: "transparent",
            stroke: "#e0e0e0",
            strokeWidth: 2,
            zIndex: 2,
          },
          {
            type: "text",
            x: 526,
            y: 390,
            width: 248,
            height: 28,
            text: "Product Name",
            fontSize: 18,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 526,
            y: 425,
            width: 248,
            height: 26,
            text: "$599",
            fontSize: 22,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "sku",
            x: 526,
            y: 458,
            width: 248,
            height: 20,
            text: "SKU: MOD-003",
            fontSize: 13,
            fontFamily: "Inter",
            color: "#999999",
            align: "center",
            zIndex: 3,
          },
          {
            type: "image",
            x: 20,
            y: 510,
            width: 248,
            height: 248,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 20,
            y: 510,
            width: 248,
            height: 248,
            fill: "transparent",
            stroke: "#e0e0e0",
            strokeWidth: 2,
            zIndex: 2,
          },
          {
            type: "text",
            x: 20,
            y: 770,
            width: 248,
            height: 28,
            text: "Product Name",
            fontSize: 18,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 20,
            y: 805,
            width: 248,
            height: 26,
            text: "$349",
            fontSize: 22,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "image",
            x: 273,
            y: 510,
            width: 248,
            height: 248,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 273,
            y: 510,
            width: 248,
            height: 248,
            fill: "transparent",
            stroke: "#e0e0e0",
            strokeWidth: 2,
            zIndex: 2,
          },
          {
            type: "text",
            x: 273,
            y: 770,
            width: 248,
            height: 28,
            text: "Product Name",
            fontSize: 18,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 273,
            y: 805,
            width: 248,
            height: 26,
            text: "$499",
            fontSize: 22,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "image",
            x: 526,
            y: 510,
            width: 248,
            height: 248,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 526,
            y: 510,
            width: 248,
            height: 248,
            fill: "transparent",
            stroke: "#e0e0e0",
            strokeWidth: 2,
            zIndex: 2,
          },
          {
            type: "text",
            x: 526,
            y: 770,
            width: 248,
            height: 28,
            text: "Product Name",
            fontSize: 18,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 526,
            y: 805,
            width: 248,
            height: 26,
            text: "$699",
            fontSize: 22,
            fontFamily: "Inter",
            color: "#000000",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 1111,
            width: 794,
            height: 12,
            fill: "#000000",
            zIndex: 1,
          },
        ],
      },
      {
        backgroundColor: "#ffffff",
        backgroundGradient: {
          from: "#ffffff",
          to: "#f8f8f8",
          direction: "vertical",
        },
        elements: [
          {
            type: "text",
            x: 97,
            y: 150,
            width: 300,
            height: 90,
            text: "CLEAN",
            fontSize: 80,
            fontFamily: "Inter",
            color: "#000000",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "text",
            x: 97,
            y: 250,
            width: 300,
            height: 90,
            text: "DESIGN",
            fontSize: 80,
            fontFamily: "Inter",
            color: "#000000",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 97,
            y: 360,
            width: 200,
            height: 6,
            fill: "#000000",
            zIndex: 2,
          },
          {
            type: "customField",
            customFieldType: "description",
            x: 97,
            y: 400,
            width: 300,
            height: 450,
            text: "Our minimal aesthetic celebrates simplicity and elegance. Each piece is designed with precision, focusing on clean lines and timeless beauty.\n\nWe believe that less is more, creating jewelry that speaks through its refined craftsmanship and attention to detail.\n\nEvery design is carefully curated to ensure it stands the test of time, becoming a cherished piece in your collection.",
            fontSize: 17,
            fontFamily: "Inter",
            color: "#333333",
            align: "left",
            fontWeight: "normal",
            zIndex: 3,
          },
          {
            type: "image",
            x: 424,
            y: 0,
            width: 370,
            height: 1123,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 424,
            y: 0,
            width: 370,
            height: 1123,
            fill: "transparent",
            stroke: "#e0e0e0",
            strokeWidth: 2,
            zIndex: 2,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 1111,
            width: 794,
            height: 12,
            fill: "#000000",
            zIndex: 4,
          },
        ],
      },
    ],
  },
  {
    templateId: "artistic-premium",
    name: "Artistic Premium",
    description:
      "Creative editorial style with bold layouts, artistic shapes, and premium aesthetics designed for A4 edge-to-edge output.",
    fontFamily: "Playfair Display",
    isBaseTemplate: true,
    userId: null,
    pages: [
      {
        backgroundColor: "#f5f1ed",
        backgroundGradient: {
          from: "#f5f1ed",
          to: "#ebe5dd",
          direction: "vertical",
        },
        elements: [
          {
            type: "shape",
            shapeType: "circle",
            x: 544,
            y: 40,
            width: 250,
            height: 250,
            fill: "#d4c4b0",
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "circle",
            x: 594,
            y: 140,
            width: 150,
            height: 150,
            fill: "#c4b09a",
            zIndex: 2,
          },
          {
            type: "text",
            x: 97,
            y: 280,
            width: 600,
            height: 100,
            text: "ARTISTIC",
            fontSize: 92,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "center",
            fontWeight: "bold",
            zIndex: 4,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 247,
            y: 270,
            width: 300,
            height: 110,
            fill: "rgba(212, 196, 176, 0.25)",
            cornerRadius: 8,
            zIndex: 3,
          },
          {
            type: "text",
            x: 97,
            y: 400,
            width: 600,
            height: 50,
            text: "Jewelry Collection",
            fontSize: 36,
            fontFamily: "Playfair Display",
            color: "#5a5a5a",
            align: "center",
            fontWeight: "normal",
            fontStyle: "italic",
            zIndex: 4,
          },
          {
            type: "text",
            x: 97,
            y: 470,
            width: 600,
            height: 40,
            text: "Where Art Meets Elegance",
            fontSize: 24,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "center",
            fontWeight: "normal",
            zIndex: 4,
          },
          {
            type: "image",
            x: 297,
            y: 560,
            width: 200,
            height: 200,
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 287,
            y: 550,
            width: 220,
            height: 220,
            fill: "transparent",
            stroke: "#c4b09a",
            strokeWidth: 4,
            cornerRadius: 12,
            zIndex: 2,
          },
          {
            type: "shape",
            shapeType: "circle",
            x: 40,
            y: 920,
            width: 120,
            height: 120,
            fill: "#d4c4b0",
            zIndex: 1,
          },
          {
            type: "text",
            x: 497,
            y: 1020,
            width: 300,
            height: 35,
            text: "2024 Edition",
            fontSize: 22,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "right",
            fontWeight: "normal",
            fontStyle: "italic",
            zIndex: 4,
          },
        ],
      },
      {
        backgroundColor: "#faf8f5",
        elements: [
          {
            type: "shape",
            shapeType: "rect",
            x: 0,
            y: 0,
            width: 794,
            height: 140,
            fill: "#2d2d2d",
            zIndex: 1,
          },
          {
            type: "text",
            x: 97,
            y: 45,
            width: 600,
            height: 60,
            text: "CURATED PIECES",
            fontSize: 42,
            fontFamily: "Playfair Display",
            color: "#faf8f5",
            align: "center",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "image",
            x: 60,
            y: 170,
            width: 360,
            height: 460,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 60,
            y: 170,
            width: 360,
            height: 460,
            fill: "rgba(212, 196, 176, 0.15)",
            cornerRadius: 8,
            zIndex: 2,
          },
          {
            type: "text",
            x: 60,
            y: 650,
            width: 360,
            height: 35,
            text: "Statement Necklace",
            fontSize: 26,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "bold",
            zIndex: 4,
          },
          {
            type: "customField",
            customFieldType: "description",
            x: 60,
            y: 695,
            width: 360,
            height: 80,
            text: "A bold statement piece that combines contemporary design with vintage elegance, featuring premium materials and exceptional craftsmanship.",
            fontSize: 15,
            fontFamily: "Playfair Display",
            color: "#5a5a5a",
            align: "left",
            fontWeight: "normal",
            zIndex: 4,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 60,
            y: 785,
            width: 360,
            height: 30,
            text: "$1,899",
            fontSize: 28,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "bold",
            zIndex: 4,
          },
          {
            type: "image",
            x: 444,
            y: 170,
            width: 290,
            height: 350,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 444,
            y: 170,
            width: 290,
            height: 350,
            fill: "rgba(196, 176, 154, 0.12)",
            cornerRadius: 6,
            zIndex: 2,
          },
          {
            type: "text",
            x: 444,
            y: 540,
            width: 290,
            height: 32,
            text: "Elegant Ring",
            fontSize: 22,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 444,
            y: 580,
            width: 290,
            height: 28,
            text: "$799",
            fontSize: 24,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "image",
            x: 444,
            y: 550,
            width: 290,
            height: 240,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 444,
            y: 550,
            width: 290,
            height: 240,
            fill: "rgba(212, 196, 176, 0.1)",
            cornerRadius: 6,
            zIndex: 2,
          },
          {
            type: "text",
            x: 444,
            y: 800,
            width: 290,
            height: 28,
            text: "Delicate Earrings",
            fontSize: 20,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "customField",
            customFieldType: "price",
            x: 444,
            y: 835,
            width: 290,
            height: 26,
            text: "$449",
            fontSize: 22,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "image",
            x: 60,
            y: 820,
            width: 360,
            height: 180,
            zIndex: 1,
          },
          {
            type: "text",
            x: 60,
            y: 1015,
            width: 360,
            height: 25,
            text: "Bracelet Collection",
            fontSize: 18,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "bold",
            zIndex: 2,
          },
          {
            type: "shape",
            shapeType: "circle",
            x: 644,
            y: 923,
            width: 150,
            height: 150,
            fill: "#d4c4b0",
            zIndex: 1,
          },
        ],
      },
      {
        backgroundColor: "#faf8f5",
        elements: [
          {
            type: "image",
            x: 0,
            y: 0,
            width: 397,
            height: 1123,
            zIndex: 1,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 397,
            y: 0,
            width: 4,
            height: 1123,
            fill: "#c4b09a",
            zIndex: 2,
          },
          {
            type: "text",
            x: 427,
            y: 120,
            width: 340,
            height: 65,
            text: "Our Story",
            fontSize: 58,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "bold",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 427,
            y: 200,
            width: 150,
            height: 3,
            fill: "#c4b09a",
            zIndex: 2,
          },
          {
            type: "customField",
            customFieldType: "description",
            x: 427,
            y: 240,
            width: 340,
            height: 550,
            text: "Artistic Premium represents our vision of jewelry as wearable art. Each collection is inspired by contemporary art movements, architectural forms, and the natural world.\n\nOur designers collaborate with master artisans to create pieces that are both striking and wearable, blending bold aesthetics with everyday elegance. We source only conflict-free materials and support sustainable practices throughout our supply chain.\n\nEvery piece tells a story, and we invite you to become part of our narrative. From the initial sketch to the final polish, each item is crafted with intention, care, and an unwavering commitment to excellence.",
            fontSize: 17,
            fontFamily: "Playfair Display",
            color: "#2d2d2d",
            align: "left",
            fontWeight: "normal",
            zIndex: 3,
          },
          {
            type: "shape",
            shapeType: "rect",
            x: 687,
            y: 820,
            width: 80,
            height: 80,
            fill: "transparent",
            stroke: "#c4b09a",
            strokeWidth: 3,
            cornerRadius: 8,
            zIndex: 2,
          },
          {
            type: "text",
            x: 427,
            y: 1020,
            width: 340,
            height: 40,
            text: "Designed by Gemora Studio",
            fontSize: 18,
            fontFamily: "Playfair Display",
            color: "#8b7355",
            align: "left",
            fontWeight: "normal",
            fontStyle: "italic",
            zIndex: 3,
          },
        ],
      },
    ],
  },
];

