import { gbToBytes } from "../../utils/index.js";

const CURRENCY_LIST = [
  { currency: "INR", symbol: "₹" },
  { currency: "USD", symbol: "$" },
  { currency: "EUR", symbol: "€" },
  { currency: "GBP", symbol: "£" },
];

// Example static conversion rates (can be adjusted)
const STATIC_PRICES = {
  INR: 1,
  USD: 0.012,
  EUR: 0.011,
  GBP: 0.0098,
};

// Helper to generate prices with symbols
const generatePrices = (amountINR) =>
  CURRENCY_LIST.map(({ currency, symbol }) => ({
    currency,
    symbol,
    amount: Math.round(amountINR * STATIC_PRICES[currency]),
    originalAmount: Math.round(amountINR * STATIC_PRICES[currency] * 2),
  }));

export const EMPTY_PLAN = {
  name: "Default Plan",
  planId: "",
  description: "empty plan with limited features",
  type: "LIMITED",
  features: {
    modelCredit: 0,
    material: 10,
    preset: 10,
    customAssets: 0,
    displayQuality: "medium",
    imageResolution: "2k",
    videoResolution: "2k",
    storageLimit: gbToBytes(0),
    maxVariant: 4,
    embed: true,
    aiImageCredit: 0,
  },
  prices: generatePrices(0),
  durationInDays: 0,
  weight: 10,
};

export const DEFAULT_PLAN = {
  name: "Free Trail",
  planId: "FREE_PLAN",
  description: "Free trail plan with limited features",
  type: "LIMITED",
  features: {
    modelCredit: 3,
    material: 10,
    preset: 10,
    customAssets: 1,
    displayQuality: "medium",
    imageResolution: "4k",
    videoResolution: "4k",
    storageLimit: gbToBytes(6),
    maxVariant: 4,
    embed: true,
    aiImageCredit: 3,
  },
  prices: generatePrices(0),
  durationInDays: 30,
  weight: 10,
};

export default [
  DEFAULT_PLAN,
  {
    name: "Starter Plan",
    planId: "plan_Ry726w7oF30qMd",
    description: "Small plan for beginners",
    type: "LIMITED",
    features: {
      modelCredit: 25,
      material: 10,
      preset: 10,
      customAssets: 15,
      displayQuality: "medium",
      imageResolution: "4k",
      videoResolution: "4k",
      storageLimit: gbToBytes(50),
      maxVariant: 7,
      embed: true,
      aiImageCredit: 50,
    },
    prices: generatePrices(1_999),
    durationInDays: null,
    weight: 20,
  },
  {
    name: "Grow Plan",
    planId: "plan_Ry72tczDybIj6N",
    description: "Growth plan with extended features",
    type: "LIMITED",
    features: {
      modelCredit: 75,
      material: 10,
      preset: 10,
      customAssets: 25,
      displayQuality: "high",
      imageResolution: "8k",
      videoResolution: "8k",
      storageLimit: gbToBytes(150),
      maxVariant: 15,
      embed: true,
      aiImageCredit: 150,
    },
    prices: generatePrices(7_999),
    durationInDays: null,
    weight: 30,
  },
  // {
  //   name: "Pro Plan",
  //   planId: "plan_ROGByV07fnAzU6",
  //   description: "Growth plan with extended features",
  //   type: "LIMITED",
  //   features: {
  //     modelCredit: 250,
  //     material: 100,
  //     preset: 100,
  //     customAssets: 75,
  //     imageCredit: 2500,
  //     videoCredit: 1000,
  //     aiImageCredit: 750,
  //     maxVariant: 10,
  //     imageResolution: "4k",
  //     videoResolution: "4k",
  //     displayQuality: "high",
  //     embed: true,
  //     multiImageFromCAD: true,
  //     multiVideoFromCAD: true,
  //     customVideoAngle: true,
  //     pdfCatalogue: true,
  //     playground: false,
  //   },
  //   prices: generatePrices(54999),
  //   durationInDays: null,
  //   weight: 40,
  // },
  // {
  //   name: "Pro Studio Plan",
  //   planId: "plan_ROGEJmz3xzX9ls",
  //   description: "Pro Studio plan with full features",
  //   type: "LIMITED",
  //   features: {
  //     modelCredit: 500,
  //     material: 100,
  //     preset: 100,
  //     customAssets: 200,
  //     imageCredit: 5000,
  //     videoCredit: 2000,
  //     aiImageCredit: 1500,
  //     maxVariant: 25,
  //     imageResolution: "8k",
  //     videoResolution: "8k",
  //     displayQuality: "ultra high",
  //     embed: true,
  //     multiImageFromCAD: true,
  //     multiVideoFromCAD: true,
  //     customVideoAngle: true,
  //     pdfCatalogue: true,
  //     playground: false,
  //   },
  //   prices: generatePrices(109999),
  //   durationInDays: null,
  //   weight: 50,
  // },
  // {
  //   name: "Pro Studio Plan",
  //   planId: "plan_ROGEJmz3xzX9ls",
  //   description: "Pro Studio plan with full features",
  //   type: "UNLIMITED",
  //   features: {
  //     modelCredit: null,
  //     material: 100,
  //     preset: 100,
  //     customAssets: 200,
  //     imageCredit: null,
  //     videoCredit: null,
  //     aiImageCredit: 1500,
  //     maxVariant: 25,
  //     imageResolution: "8k",
  //     videoResolution: "8k",
  //     displayQuality: "ultra high",
  //     embed: true,
  //     multiImageFromCAD: true,
  //     storageLimit: gbToBytes(100), // 100 gb
  //     multiVideoFromCAD: true,
  //     customVideoAngle: true,
  //     pdfCatalogue: true,
  //     playground: false,
  //   },
  //   prices: generatePrices(109999),
  //   durationInDays: 365,
  //   weight: 50,
  // },
];
