export const EMPTY_PLAN = {
  name: "Free Trail",
  planId: "",
  description: "empty plan with limited features",
  type: "order",
  features: {
    modelCredit: 0,
    material: 10,
    preset: 10,
    customAssets: 1,
    imageResolution: "2k",
    videoResolution: "2k",
    displayQuality: "medium",
    singleImageGeneration: 10,
    multiImageGeneration: 2,
    customVideoAngle: true,
    embed: true,
    aiImageGeneration: true,
    aiImageCredit: 0,
    multiImageFromCAD: true,
    pdfCatalogue: true,
    playground: false,
  },
  prices: [{ currency: "INR", amount: 0 }],
  durationInDays: 0,
  weight: 10,
};

export const DEFAULT_PLAN = {
  name: "Free Trail",
  planId: "",
  description: "Free trail plan with limited features",
  type: "order",
  features: {
    modelCredit: 3,
    material: 100,
    preset: 100,
    customAssets: 1,
    imageResolution: "2k",
    videoResolution: "2k",
    displayQuality: "medium",
    singleImageGeneration: 10,
    multiImageGeneration: 2,
    customVideoAngle: true,
    embed: true,
    aiImageGeneration: true,
    aiImageCredit: 3,
    multiImageFromCAD: true,
    pdfCatalogue: true,
    playground: false,
  },
  prices: [{ currency: "INR", amount: 0 }],
  durationInDays: 3,
  weight: 10,
};

export default [
  {
    name: "Starter Plan",
    planId: "plan_RKjWPFVJZNFt7l",
    description: "Starter plan with limited features",
    type: "subscription",
    features: {
      modelCredit: 100,
      material: 100,
      preset: 100,
      customAssets: 5,
      imageResolution: "4k",
      videoResolution: "4k",
      displayQuality: "high",
      singleImageGeneration: Number.MAX_SAFE_INTEGER,
      multiImageGeneration: 4,
      customVideoAngle: true,
      embed: true,
      aiImageGeneration: true,
      aiImageCredit: 300,
      multiImageFromCAD: true,
      pdfCatalogue: true,
      playground: false,
    },
    prices: [{ currency: "INR", amount: 34999 }],
    durationInDays: 30,
    weight: 30,
  },
  {
    name: "Growth Plan",
    planId: "plan_RKjXLhQxbdT3rL",
    description: "Growth plan with extended features",
    type: "subscription",
    features: {
      modelCredit: 250,
      material: 100,
      preset: 100,
      customAssets: 10,
      imageResolution: "4k",
      videoResolution: "4k",
      displayQuality: "high",
      singleImageGeneration: Number.MAX_SAFE_INTEGER,
      multiImageGeneration: 10,
      customVideoAngle: true,
      embed: true,
      aiImageGeneration: true,
      aiImageCredit: 750,
      multiImageFromCAD: true,
      pdfCatalogue: true,
      playground: false,
    },
    prices: [{ currency: "INR", amount: 79999 }],
    durationInDays: 30,
    weight: 40,
  },
  {
    name: "Pro Studio Plan",
    planId: "plan_RKjXdutBCioAhq",
    description: "Pro Studio plan with full features",
    type: "subscription",
    features: {
      modelCredit: 500,
      material: 100,
      preset: 100,
      customAssets: Number.MAX_SAFE_INTEGER, // Infinite
      imageResolution: "8k",
      videoResolution: "8k",
      displayQuality: "high",
      singleImageGeneration: Number.MAX_SAFE_INTEGER,
      multiImageGeneration: Number.MAX_SAFE_INTEGER,
      customVideoAngle: true,
      embed: true,
      aiImageGeneration: true,
      aiImageCredit: 1500,
      multiImageFromCAD: true,
      pdfCatalogue: true,
      playground: false,
    },
    prices: [{ currency: "INR", amount: 149999 }],
    durationInDays: 30,
    weight: 50,
  },
];
