const CREDITS = [
  {
    name: "Starter Pack",
    planId: "TOP_UP",
    description: "15 model credits for quick experiments",
    type: "modelCredit",
    features: { modelCredit: 15 },
    prices: [{ currency: "INR", amount: 0 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Basic Pack",
    planId: "TOP_UP",
    description: "50 model credits to get started",
    type: "modelCredit",
    features: { modelCredit: 50 },
    prices: [{ currency: "INR", amount: 0 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Standard Pack",
    planId: "TOP_UP",
    description: "100 model credits for regular usage",
    type: "modelCredit",
    features: { modelCredit: 100 },
    prices: [{ currency: "INR", amount: 0 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Pro Pack",
    planId: "TOP_UP",
    description: "500 model credits for professionals",
    type: "modelCredit",
    features: { modelCredit: 500 },
    prices: [{ currency: "INR", amount: 0 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
];
const IMAGE = [
  {
    name: "Starter Image Pack",
    planId: "TOP_UP",
    description: "150 image credits for small tasks",
    type: "imageCredit",
    features: { imageCredit: 150 },
    prices: [{ currency: "INR", amount: 750 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Basic Image Pack",
    planId: "TOP_UP",
    description: "500 image credits for consistent usage",
    type: "imageCredit",
    features: { imageCredit: 500 },
    prices: [{ currency: "INR", amount: 2500 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Standard Image Pack",
    planId: "TOP_UP",
    description: "1000 image credits for larger projects",
    type: "imageCredit",
    features: { imageCredit: 1000 },
    prices: [{ currency: "INR", amount: 5000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Pro Image Pack",
    planId: "TOP_UP",
    description: "5000 image credits for professionals",
    type: "imageCredit",
    features: { imageCredit: 5000 },
    prices: [{ currency: "INR", amount: 25000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
];

const VIDEO = [
  {
    name: "Starter Video Pack",
    planId: "TOP_UP",
    description: "120 video credits for quick projects",
    type: "videoCredit",
    features: { videoCredit: 120 },
    prices: [{ currency: "INR", amount: 1200 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Basic Video Pack",
    planId: "TOP_UP",
    description: "400 video credits for growing needs",
    type: "videoCredit",
    features: { videoCredit: 400 },
    prices: [{ currency: "INR", amount: 4000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Standard Video Pack",
    planId: "TOP_UP",
    description: "800 video credits for regular usage",
    type: "videoCredit",
    features: { videoCredit: 800 },
    prices: [{ currency: "INR", amount: 8000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Pro Video Pack",
    planId: "TOP_UP",
    description: "4000 video credits for professionals",
    type: "videoCredit",
    features: { videoCredit: 4000 },
    prices: [{ currency: "INR", amount: 40000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
];

const AI_IMAGE = [
  {
    name: "Starter AI Image Pack",
    planId: "TOP_UP",
    description: "1200 AI image credits for testing ideas",
    type: "aiImageCredit",
    features: { aiImageCredit: 1200 },
    prices: [{ currency: "INR", amount: 12000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Basic AI Image Pack",
    planId: "TOP_UP",
    description: "4000 AI image credits for creative work",
    type: "aiImageCredit",
    features: { aiImageCredit: 4000 },
    prices: [{ currency: "INR", amount: 40000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Standard AI Image Pack",
    planId: "TOP_UP",
    description: "8000 AI image credits for heavy projects",
    type: "aiImageCredit",
    features: { aiImageCredit: 8000 },
    prices: [{ currency: "INR", amount: 80000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
  {
    name: "Pro AI Image Pack",
    planId: "TOP_UP",
    description: "40000 AI image credits for professionals",
    type: "aiImageCredit",
    features: { aiImageCredit: 40000 },
    prices: [{ currency: "INR", amount: 400000 }],
    durationInDays: Number.MAX_SAFE_INTEGER,
    weight: 0,
    isActive: true,
  },
];

export default [...CREDITS, ...IMAGE, ...VIDEO, ...AI_IMAGE];
